#!/usr/bin/env python3
"""promote_visual — aggregate visual-skill drift events into a learned-patterns digest.

The fakematt-email/promote.py mines text-substitution patterns from corrections.md
files. Visual skills (graphic-layout, blog-imagery) record drift events instead —
the lesson is "this asset got re-rendered after review/generation," and the
aggregable signal is frequency-by-axis (target_kind, label, provider).

This script reads BOTH visual-skill corrections.md files, counts drift events,
and writes a digest to `MattZerg/_style/visual_iteration_patterns.md` that
ranks the noisiest paths so future graphic/imagery work can anticipate where
iteration will land.

Designed to run daily 6:50am alongside the FM voice promote.py.

Usage:
    python3 ~/.claude/skills/graphic-layout/promote_visual.py [--threshold N]

Threshold default = 3 (an axis must show ≥3 drift events to surface).
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from collections import Counter
from pathlib import Path

def _pick_vault() -> Path:
    """Prefer the live Obsidian vault (canonical); fall back to the legacy iCloud
    path or the TCC mirror only when canonical is unavailable.

    NOTE 2026-06-30: canonical moved to ~/Obsidian/Zerg — the old iCloud Documents
    path is now a near-empty shell. The previous 'prefer iCloud' logic was readable
    (so it always won) and stranded learned _style digests in that shell while the
    real vault went stale. See Growth/publishing/_audit-2026-06-30-nobody-reads-code.md §4.
    """
    canonical = Path.home() / "Obsidian" / "Zerg" / "MattZerg"
    icloud = Path("/Users/mattheweisner/Library/Mobile Documents/iCloud~md~obsidian/Documents/Zerg/MattZerg")
    mirror = Path.home() / ".zerg-vault-mirror" / "MattZerg"
    for cand in (canonical, icloud, mirror):
        try:
            if cand.exists() and any(cand.iterdir()):
                return cand
        except (PermissionError, OSError):
            continue
    return canonical


VAULT = _pick_vault()
DIGEST = VAULT / "_style" / "visual_iteration_patterns.md"
GRAPHIC_CORRECTIONS = Path.home() / ".claude" / "skills" / "graphic-layout" / "corrections.md"
IMAGERY_CORRECTIONS = Path.home() / ".claude" / "skills" / "blog-imagery" / "corrections.md"


def parse_graphic_corrections() -> Counter:
    """graphic-layout corrections — count by target_kind."""
    if not GRAPHIC_CORRECTIONS.exists():
        return Counter()
    text = GRAPHIC_CORRECTIONS.read_text()
    # Each entry's heading is "## YYYY-MM-DD — <target_kind> re-rendered after review"
    return Counter(re.findall(r"## \d{4}-\d{2}-\d{2} — (\S+) re-rendered after review", text))


def parse_imagery_corrections() -> tuple[Counter, Counter]:
    """blog-imagery corrections — count by label and by provider."""
    if not IMAGERY_CORRECTIONS.exists():
        return Counter(), Counter()
    text = IMAGERY_CORRECTIONS.read_text()
    by_label = Counter(re.findall(r"## \d{4}-\d{2}-\d{2} — \S+ / (\S+) regenerated", text))
    by_provider = Counter(re.findall(r"- provider: `([^`]+)`", text))
    return by_label, by_provider


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--threshold", type=int, default=3)
    args = ap.parse_args()

    by_kind = parse_graphic_corrections()
    by_label, by_provider = parse_imagery_corrections()

    today = dt.date.today().isoformat()
    DIGEST.parent.mkdir(parents=True, exist_ok=True)
    out = [
        "---",
        "tags: visual, learning, iteration",
        f"updated: {today}",
        "---",
        "",
        "# Visual iteration patterns",
        "",
        "Auto-generated by `promote_visual.py` from drift events captured by",
        "`graphic-layout/learn.py` and `blog-imagery/learn.py`. Each section",
        f"surfaces axes that crossed the ≥{args.threshold} re-render threshold.",
        "",
        "Reading this digest before kicking off a graphic / imagery run gives",
        "an anticipated-iteration prior: where past you re-rendered most.",
        "",
    ]

    if not (by_kind or by_label or by_provider):
        out.append("*No drift events captured yet — neither learn.py has logged data.*")
        out.append("")
        DIGEST.write_text("\n".join(out))
        print("[promote_visual] no drift data; wrote empty digest")
        return 0

    out += ["## graphic-layout: re-renders by `target_kind`", ""]
    promoted = [(k, n) for k, n in by_kind.most_common() if n >= args.threshold]
    if promoted:
        out += ["| target_kind | re-renders |", "|---|---|"]
        out += [f"| `{k}` | {n} |" for k, n in promoted]
    else:
        out.append(f"*No target_kind crossed the ≥{args.threshold} threshold.*")
    out.append("")

    out += ["## blog-imagery: re-renders by asset `label`", ""]
    promoted = [(k, n) for k, n in by_label.most_common() if n >= args.threshold]
    if promoted:
        out += ["| label | re-renders |", "|---|---|"]
        out += [f"| `{k}` | {n} |" for k, n in promoted]
    else:
        out.append(f"*No label crossed the ≥{args.threshold} threshold.*")
    out.append("")

    out += ["## blog-imagery: re-renders by `provider`", ""]
    promoted = [(k, n) for k, n in by_provider.most_common() if n >= args.threshold]
    if promoted:
        out += ["| provider | re-renders |", "|---|---|"]
        out += [f"| `{k}` | {n} |" for k, n in promoted]
    else:
        out.append(f"*No provider crossed the ≥{args.threshold} threshold.*")
    out.append("")

    DIGEST.write_text("\n".join(out))
    total = sum(by_kind.values()) + sum(by_label.values())
    print(f"[promote_visual] {total} total drift events, threshold={args.threshold}")
    print(f"  → {DIGEST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
