#!/usr/bin/python3
"""generate_top: write `Ideas/_top.md` — one-page scannable summary of the
highest-quality ideas, per category, with title + one-line + tags.

Selection per category:
  1. Top by depth*viability score (tie-break by conviction, then last_touched)
  2. Up to N per category (default 12)

Output is a markdown file with section per category. No Dataview required.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

_LIB = Path(__file__).resolve().parent / "_lib"
if str(_LIB) not in sys.path:
    sys.path.insert(0, str(_LIB))

from frontmatter import read_file  # noqa: E402
from idea_io import iter_all_ideas  # noqa: E402
from vault_paths import CATEGORIES, IDEAS_ROOT  # noqa: E402

CATEGORY_LABELS = {
    "zerg-product": "🚀 Zerg — Product",
    "zerg-content": "📝 Zerg — Content",
    "zerg-tooling": "🔧 Zerg — Tooling",
    "personal-venture": "💼 Personal — Ventures",
    "personal-life": "🌱 Personal — Life",
    "shopping": "🛒 Shopping",
    "research": "🔬 Research",
}

CONVICTION_RANK = {"high": 3, "medium": 2, "low": 1, None: 0}


def first_idea_line(body: str) -> str:
    """Extract the first non-empty line under `## Idea`."""
    in_section = False
    for line in (body or "").splitlines():
        s = line.strip()
        if s.startswith("## Idea"):
            in_section = True
            continue
        if in_section and s.startswith("## "):
            break
        if in_section and s and not s.startswith("("):
            return s
    return ""


def score(meta: dict) -> tuple[int, int, str]:
    """Sort key: -(depth*viability), -conviction_rank, -last_touched."""
    d = meta.get("depth") or 0
    v = meta.get("viability") or 0
    conv = CONVICTION_RANK.get(meta.get("conviction"), 0)
    lt = meta.get("last_touched") or meta.get("created") or ""
    return (-(int(d) * int(v)), -conv, lt and f"!{lt}" or "")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--per-category", type=int, default=12)
    ap.add_argument("--output", default=str(IDEAS_ROOT / "_top.md"))
    args = ap.parse_args()

    by_cat: dict[str, list[tuple[dict, Path]]] = {c: [] for c in CATEGORIES}
    for p in iter_all_ideas(include_inbox=False, include_archive=False):
        try:
            meta, body = read_file(p)
        except Exception:
            continue
        cat = meta.get("category")
        if cat in by_cat:
            by_cat[cat].append((meta, body, p))  # type: ignore

    lines = [
        "# Top Ideas — single-page snapshot",
        "",
        "*Auto-generated by `idea-backlog/generate_top.py`. Sorted within each category by `depth × viability` score, then conviction, then last-touched.*",
        "",
        "Capture: `/idea-backlog capture` · Browse: [[README]] · Schema: [[_meta/schema]]",
        "",
    ]

    for cat in CATEGORIES:
        items = by_cat.get(cat, [])
        if not items:
            continue
        items.sort(key=lambda r: score(r[0]))
        items = items[: args.per_category]

        lines.append(f"## {CATEGORY_LABELS.get(cat, cat)}  ({len(by_cat[cat])} active)")
        lines.append("")
        lines.append("| # | Idea | Conv | D×V | Tags |")
        lines.append("|---|---|---|---|---|")
        for i, (meta, body, p) in enumerate(items, 1):
            title = meta.get("title") or p.stem
            one = first_idea_line(body)
            display = title if not one or one.lower() == title.lower() else f"**{title}** — {one}"
            display = display.replace("|", "\\|")[:180]
            conv = (meta.get("conviction") or "?")[:1].upper()
            d = meta.get("depth") or "?"
            v = meta.get("viability") or "?"
            dv = f"{d}×{v}" if d != "?" and v != "?" else "—"
            tags = ", ".join((meta.get("tags") or [])[:4])
            tags = tags.replace("|", "\\|")
            link = f"[[Ideas/{p.parent.name}/{p.stem}]]"
            lines.append(f"| {i} | {display}  {link} | {conv} | {dv} | {tags} |")
        lines.append("")

    out = Path(args.output)
    out.write_text("\n".join(lines))
    print(f"wrote {out}")
    total = sum(len(v) for v in by_cat.values())
    sampled = sum(min(args.per_category, len(v)) for v in by_cat.values())
    print(f"  {total} active ideas total; surfaced top {sampled} ({args.per_category}/category)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
