#!/usr/bin/env python3
"""Regenerate the bulk markdown ledgers (prospects.md, bd-targets.md, experiments.md)
from the per-entity files. The per-entity files are the source of truth;
these ledgers are auto-generated human-readable indexes.

Idempotent. Only writes when content changes.

Usage:
    python3 ~/.claude/skills/gtm-hub/scripts/regen_ledgers.py
"""
from __future__ import annotations

import datetime as dt
import sys
from pathlib import Path

THIS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(THIS_DIR))

from lib.entities import GROWTH_DIR, load_by_type, read_growth_file, write_growth_file  # noqa: E402


HEADER = (
    "<!-- AUTO-GENERATED by `gtm-hub regen-ledgers` from per-entity files. "
    "Edit the entity files under Growth/<type>/<id>.md, not this file. -->"
)


def _write_if_changed(path: Path, content: str) -> bool:
    """Write a ledger file via the TCC-resilient cascade.

    `path` is treated as Growth-relative — only its name relative to
    GROWTH_DIR matters. If reading current content fails (TCC under
    launchd), assume changed and write.
    """
    try:
        rel = str(path.resolve().relative_to(GROWTH_DIR.resolve()))
    except (ValueError, OSError):
        rel = path.name
    existing = read_growth_file(rel)
    if existing == content:
        return False
    write_growth_file(rel, content)
    return True


def regen_prospects() -> bool:
    entities = load_by_type("prospect")
    if not entities:
        return False
    today = dt.date.today().isoformat()
    by_stage: dict[str, list] = {}
    for e in entities:
        by_stage.setdefault(e.meta.get("status", "?"), []).append(e)
    lines = [
        "# Solutions Prospect Pipeline",
        "",
        HEADER,
        "",
        f"_Generated {today} from `Growth/prospects/<slug>.md` per-entity files._",
        "",
        "## Stages",
        "",
        "`inbound` → `qualified` → `scoped` → `proposal-out` → `won` / `lost`",
        "",
    ]
    stage_order = ["proposal-out", "scoped", "qualified", "inbound", "won", "lost"]
    for stage in stage_order:
        rows = by_stage.get(stage) or []
        if not rows:
            continue
        lines.append(f"## {stage} ({len(rows)})")
        lines.append("")
        lines.append("| Company | Source | Score | Owner | Last touch | Next | Referrer | Notes |")
        lines.append("|---|---|---|---|---|---|---|---|")
        for e in sorted(rows, key=lambda x: -(x.meta.get("score") or 0) if isinstance(x.meta.get("score"), (int, float)) else 0):
            m = e.meta
            cells = [
                m.get("company") or m.get("title") or e.id,
                m.get("source", ""),
                str(m.get("score", "")),
                m.get("owner", ""),
                m.get("last_touch", ""),
                (m.get("next_action") or "").replace("|", "/"),
                str(m.get("referrer") or "—"),
                (str(m.get("notes") or "")).replace("|", "/"),
            ]
            lines.append("| " + " | ".join(c if c not in (None, "") else "—" for c in cells) + " |")
        lines.append("")
    text = "\n".join(lines).rstrip() + "\n"
    return _write_if_changed(GROWTH_DIR / "prospects.md", text)


def regen_bd() -> bool:
    entities = load_by_type("bd_target")
    if not entities:
        return False
    today = dt.date.today().isoformat()
    by_cat: dict[str, list] = {}
    for e in entities:
        by_cat.setdefault(e.meta.get("category") or "uncategorized", []).append(e)
    lines = [
        "# BD Targets — Product Partnerships, Integrations, Podcasts, Ecosystem",
        "",
        HEADER,
        "",
        f"_Generated {today} from `Growth/bd/<slug>.md` per-entity files._",
        "",
        "Status legend: `planned` · `outreach` · `engaged` · `paused` · `closed-won` · `closed-lost`",
        "",
    ]
    cat_order = ["integration", "co-marketing", "podcast", "ecosystem", "uncategorized"]
    for cat in cat_order + sorted(set(by_cat) - set(cat_order)):
        rows = by_cat.get(cat) or []
        if not rows:
            continue
        lines.append(f"## {cat} ({len(rows)})")
        lines.append("")
        lines.append("| Target | Status | Owner | Last touch | Why | Next |")
        lines.append("|---|---|---|---|---|---|")
        for e in sorted(rows, key=lambda x: (x.meta.get("status") or "", x.meta.get("title") or x.id)):
            m = e.meta
            cells = [
                m.get("title") or m.get("target") or e.id,
                m.get("status", ""),
                m.get("owner", ""),
                m.get("last_touch", ""),
                (m.get("why") or "").replace("|", "/"),
                (m.get("next_action") or "").replace("|", "/"),
            ]
            lines.append("| " + " | ".join(c if c not in (None, "") else "—" for c in cells) + " |")
        lines.append("")
    text = "\n".join(lines).rstrip() + "\n"
    return _write_if_changed(GROWTH_DIR / "bd-targets.md", text)


def regen_experiments() -> bool:
    entities = load_by_type("experiment")
    if not entities:
        return False
    today = dt.date.today().isoformat()
    by_status: dict[str, list] = {}
    for e in entities:
        by_status.setdefault(e.meta.get("status", "?"), []).append(e)
    lines = [
        "# Experiments Ledger",
        "",
        HEADER,
        "",
        f"_Generated {today} from `Growth/experiments/<id>.md` per-entity files._",
        "",
    ]
    status_order = ["running", "proposed", "won", "killed", "inconclusive"]
    for status in status_order + sorted(set(by_status) - set(status_order)):
        rows = by_status.get(status) or []
        if not rows:
            continue
        lines.append(f"## {status} ({len(rows)})")
        lines.append("")
        lines.append("| ID | Title | Phase | RICE | Kill date | Last touch |")
        lines.append("|---|---|---|---|---|---|")
        def _key(e):
            return (-(e.meta.get("rice_score") or 0) if isinstance(e.meta.get("rice_score"), (int, float)) else 0, e.id)
        for e in sorted(rows, key=_key):
            m = e.meta
            cells = [
                e.id,
                (m.get("title") or m.get("name") or "")[:60],
                m.get("phase", ""),
                str(m.get("rice_score") or m.get("RICE_score") or ""),
                m.get("kill_date", ""),
                m.get("last_touch", ""),
            ]
            lines.append("| " + " | ".join(c if c not in (None, "") else "—" for c in cells) + " |")
        lines.append("")
    text = "\n".join(lines).rstrip() + "\n"
    return _write_if_changed(GROWTH_DIR / "experiments.md", text)


def main() -> int:
    p_changed = regen_prospects()
    b_changed = regen_bd()
    e_changed = regen_experiments()
    for name, changed in [("prospects.md", p_changed), ("bd-targets.md", b_changed), ("experiments.md", e_changed)]:
        print(f"  {'WROTE' if changed else 'unchanged'}: {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
