#!/usr/bin/env python3
"""Render Growth/README.md from index.json + decisions.json.

Layout follows feedback_dashboard_must_drive_action.md (lead one action, hide healthy,
ASCII-rich per feedback_ascii_layout_patterns_library.md).
"""
from __future__ import annotations

import datetime as dt
import json
import sys
from pathlib import Path

THIS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(THIS_DIR))

from lib.entities import GROWTH_DIR, META_DIR, read_growth_file, write_growth_file  # noqa: E402
from lib.schema import parse_date  # noqa: E402


PHASE_1_START = dt.date(2026, 5, 5)
PHASE_1_DAYS = 30
DECISIONS_VISIBLE_DEFAULT = 5

DEFAULT_CONFIG = {
    "sections": [
        "decisions",
        "debt",
        "phase_status",
        "experiments",
        "content",
        "bd",
        "prospects",
        "launches",
        "themes",
        "workstreams",
        "crosslinks",
    ],
    "decisions": {"visible_count": DECISIONS_VISIBLE_DEFAULT},
    "hide_healthy_sections": True,
    "row_caps": {
        "experiments": 10,
        "content": 20,
        "bd": 20,
        "prospects": 20,
        "launches": 10,
    },
}


def load_config() -> dict:
    """Read render-config.yaml. Tiny YAML — sufficient subset, no external dep."""
    path = META_DIR / "render-config.yaml"
    if not path.exists():
        return DEFAULT_CONFIG
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return DEFAULT_CONFIG
    cfg = dict(DEFAULT_CONFIG)
    sections: list[str] = []
    row_caps: dict[str, int] = {}
    decisions_cfg: dict[str, int] = {}
    mode = None
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        # Top-level mapping starters
        stripped = line.lstrip()
        indent = len(line) - len(stripped)
        if indent == 0 and stripped.endswith(":"):
            mode = stripped[:-1]
            continue
        if indent == 0 and ":" in stripped:
            k, _, v = stripped.partition(":")
            v = v.strip()
            if v.lower() in ("true", "false"):
                cfg[k.strip()] = v.lower() == "true"
            mode = None
            continue
        if mode == "sections" and stripped.startswith("- "):
            sections.append(stripped[2:].strip())
        elif mode == "row_caps" and ":" in stripped:
            k, _, v = stripped.partition(":")
            try:
                row_caps[k.strip()] = int(v.strip())
            except ValueError:
                pass
        elif mode == "decisions" and ":" in stripped:
            k, _, v = stripped.partition(":")
            try:
                decisions_cfg[k.strip()] = int(v.strip())
            except ValueError:
                pass
    if sections:
        cfg["sections"] = sections
    if row_caps:
        cfg["row_caps"] = row_caps
    if decisions_cfg:
        cfg["decisions"] = decisions_cfg
    return cfg


def _bar(filled: int, total: int, width: int = 10) -> str:
    if total <= 0:
        return "░" * width
    pct = min(1.0, filled / total)
    n = int(round(pct * width))
    return "▓" * n + "░" * (width - n)


def _decision_icon(rule: str) -> str:
    if "overdue" in rule:
        return "⚠"
    if "approaching" in rule:
        return "🟡"
    if rule.startswith("metric"):
        return "📊"
    if rule.startswith("content"):
        return "📝"
    if rule.startswith("launch"):
        return "🚀"
    if rule.startswith("prospect"):
        return "💼"
    if rule.startswith("bd"):
        return "🤝"
    return "•"


def render_header(today: dt.date) -> list[str]:
    return [
        "# Zerg GTM Hub",
        "",
        f"_Generated {today.isoformat()} · Source of truth for growth/marketing/content/publishing/sales._",
        "",
        "_Auto-regenerated by `gtm-hub regenerate`. Manual edits to this file will be overwritten — edit the per-entity files under `Growth/<type>/<id>.md` instead._",
        "",
    ]


def render_open_decisions(entities: list[dict], today: dt.date) -> list[str]:
    """Render human-curated open decisions as a numbered briefing.

    Report style: each decision is a numbered section (#1 of N) with urgency
    band, headline title, question, context, A/B/C options with inline
    `gtm decide` commands, and downstream-impact list.
    """
    decs = [
        e for e in entities
        if e["type"] == "decision" and e["status"] in ("open", "deferred")
    ]
    if not decs:
        return []

    def _urgency_key(e: dict) -> tuple:
        d = e.get("deadline") or ""
        try:
            dl = dt.date.fromisoformat(d) if d else None
        except (ValueError, TypeError):
            dl = None
        if dl:
            return (0, (dl - today).days, e.get("id") or "")
        unblocks = e.get("unblocks") or []
        return (1, -(len(unblocks) if isinstance(unblocks, list) else 0), e.get("id") or "")

    decs.sort(key=_urgency_key)
    n = len(decs)
    lines = [
        "## 🤔 Open decisions — your plate",
        "",
        f"_{n} decision{'s' if n != 1 else ''} awaiting your call. "
        "Each one is below — review options, then run the `gtm decide` command "
        "for your choice (or `gtm defer <id>` to kick the can)._",
        "",
        "---",
        "",
    ]

    for i, e in enumerate(decs[:5], 1):
        eid = e.get("id") or ""
        title = e.get("title") or eid
        deadline_str = e.get("deadline") or ""
        unblocks = e.get("unblocks") or []
        unblocks_n = len(unblocks) if isinstance(unblocks, list) else 0

        # Urgency band
        urgency_icon = "⚪"
        urgency_label = "no deadline"
        if deadline_str:
            try:
                dl = dt.date.fromisoformat(deadline_str)
                delta = (dl - today).days
                long_date = dl.strftime("%b %-d, %Y")
                if delta < 0:
                    urgency_icon = "🔴"
                    urgency_label = f"OVERDUE by {-delta}d (deadline was {long_date})"
                elif delta == 0:
                    urgency_icon = "🔴"
                    urgency_label = f"DUE TODAY ({long_date})"
                elif delta <= 7:
                    urgency_icon = "🟠"
                    urgency_label = f"DUE {long_date} ({delta} day{'s' if delta != 1 else ''})"
                elif delta <= 21:
                    urgency_icon = "🟡"
                    urgency_label = f"due {long_date} ({delta} days)"
                else:
                    urgency_icon = "🟢"
                    urgency_label = f"due {long_date} ({delta} days)"
            except ValueError:
                urgency_label = f"deadline {deadline_str}"

        status_pill = "" if e["status"] == "open" else f" · _[{e['status']}]_"
        unblocks_str = f" · unblocks {unblocks_n} downstream" if unblocks_n else ""

        # Header: "DECISION 1 of 3 · 🟠 DUE May 19 (8 days) · unblocks 4 downstream"
        lines.append(
            f"### DECISION {i} of {n} · {urgency_icon} {urgency_label}{unblocks_str}{status_pill}"
        )
        lines.append("")
        # Title as a level-4 head — big and readable
        lines.append(f"#### {title}")
        lines.append("")

        # Question
        question = e.get("question") or ""
        if question:
            lines.append("**The call.**")
            for q_line in str(question).strip().splitlines():
                lines.append(q_line)
            lines.append("")

        # Context
        context = e.get("context") or ""
        if context:
            lines.append("**Why it matters.**")
            for c_line in str(context).strip().splitlines():
                lines.append(c_line)
            lines.append("")

        # Options as A / B / C
        options = e.get("options") or []
        if isinstance(options, list) and options:
            lines.append("**Options.**")
            lines.append("")
            for opt_i, opt in enumerate(options):
                if not isinstance(opt, dict):
                    continue
                letter = chr(ord("A") + opt_i) if opt_i < 26 else f"#{opt_i+1}"
                key = opt.get("key", "?")
                label = opt.get("label", key)
                lines.append(f"**{letter}.** {label}")
                impl = opt.get("implications")
                if impl:
                    for impl_line in str(impl).strip().splitlines():
                        lines.append(f"   {impl_line}")
                lines.append(f"   → `gtm decide {eid} {key}`")
                lines.append("")

        # Downstream impact — auto-derived projects this decision blocks
        blocks_projects = e.get("blocks_projects") or []
        if isinstance(blocks_projects, list) and blocks_projects:
            lines.append(f"**Blocks {len(blocks_projects)} project{'s' if len(blocks_projects) != 1 else ''}:**")
            for bp in blocks_projects:
                target = bp.get("target_date") or "no deadline"
                rag = bp.get("rag") or ""
                icon = "🔴" if bp.get("status") == "blocked" else {"red": "🔴", "amber": "🟡", "green": "🟢"}.get(rag, "⚪")
                lines.append(f"- {icon} **{bp.get('title', bp.get('id'))}** (target {target})")
            lines.append("")
        # Hand-written unblocks (often non-project artifacts)
        if isinstance(unblocks, list) and unblocks:
            lines.append("**Other downstream:**")
            for u in unblocks:
                lines.append(f"- `{u}`")
            lines.append("")

        # Defer escape hatch
        lines.append(f"_Not ready? `gtm defer {eid}` to kick this back._")
        lines.append("")
        lines.append("---")
        lines.append("")

    if len(decs) > 5:
        lines.append(
            f"_+{len(decs) - 5} more open decisions — see `decisions/` directory._"
        )
        lines.append("")
    return lines


def render_decisions(decisions: list[dict], limit: int = DECISIONS_VISIBLE_DEFAULT) -> list[str]:
    """Diversify by rule so ≤limit visible per `feedback_dashboard_must_drive_action.md`.

    Drops `kind == "backlog"` rules — those surface in `render_debt()` so the
    decisions panel only carries actionable this-week calls.
    """
    from lib.rules import diversify
    from act import hint_for_decision

    lines = ["## ▶ Triage (rule-derived signals)"]
    if not decisions:
        lines += ["", "_All rule-derived signals quiet. 🟢_", ""]
        return lines

    # Filter out:
    #   - decision.open (covered in full above by render_open_decisions)
    #   - kind=backlog (covered separately by render_debt)
    decisions = [
        d for d in decisions
        if d.get("rule") != "decision.open" and d.get("kind", "decision") != "backlog"
    ]
    if not decisions:
        return ["## ▶ Triage", "", "_All rule-derived signals quiet. 🟢_", ""]
    visible = diversify(decisions, limit=limit)
    lines += [""]
    for i, (d, siblings, names) in enumerate(visible, 1):
        icon = _decision_icon(d["rule"])
        # System rules have no entity file — omit the link
        if d.get("entity_path"):
            ref = f" — [`{d['entity_id']}`]({_relpath(d['entity_path'])})"
        else:
            ref = ""
        if siblings:
            shown = ", ".join(f"`{n}`" for n in names)
            extra = f" +{siblings - len(names)}" if siblings > len(names) else ""
            tail = f" _(+{siblings} more: {shown}{extra})_"
        else:
            tail = ""
        hint = hint_for_decision(d.get("rule", ""), d.get("entity_id", ""))
        hint_str = f" → `{hint}`" if hint else ""
        lines.append(f"{i}. {icon} {d['message']}{ref}{tail}{hint_str}")
    rolled_up_other = len(decisions) - sum(1 + s for _, s, _ in visible)
    if rolled_up_other > 0:
        lines.append("")
        lines.append(f"_+{rolled_up_other} more in `_meta/decisions.json` (other rules)._")
    lines.append("")
    return lines


def render_debt(decisions: list[dict], limit: int = 3) -> list[str]:
    """Render `kind=backlog` rules as a separate Measurement-debt panel.

    Same diversification pass as the decisions panel (one row per rule, sibling
    count for the rest) but visually demoted so it doesn't crowd out this-week
    calls. Hidden entirely when there's no backlog signal.
    """
    from lib.rules import diversify

    backlog = [d for d in decisions if d.get("kind") == "backlog"]
    if not backlog:
        return []
    visible = diversify(backlog, limit=limit)
    lines = [
        "## 📚 Measurement debt",
        "",
        "_Known cleanup epics — not this-week decisions. Surfaced here so they "
        "don't crowd the triage panel above._",
        "",
    ]
    for d, siblings, names in visible:
        icon = _decision_icon(d["rule"])
        if d.get("entity_path"):
            ref = f" — [`{d['entity_id']}`]({_relpath(d['entity_path'])})"
        else:
            ref = ""
        if siblings:
            shown = ", ".join(f"`{n}`" for n in names)
            extra = f" +{siblings - len(names)}" if siblings > len(names) else ""
            tail = f" _(+{siblings} more: {shown}{extra})_"
        else:
            tail = ""
        lines.append(f"- {icon} {d['message']}{ref}{tail}")
    rolled_up_other = len(backlog) - sum(1 + s for _, s, _ in visible)
    if rolled_up_other > 0:
        lines.append("")
        lines.append(f"_+{rolled_up_other} more backlog rows in `_meta/decisions.json`._")
    lines.append("")
    return lines


def _relpath(p: str) -> str:
    """Return a Growth/-relative path for a markdown link.

    Entities are loaded from the local mirror (read-tolerant) but the README
    lives in canonical iCloud — so links must be relative to canonical Growth/.
    We compare the trailing components: if the path includes `/Growth/<rest>`,
    return `<rest>`, regardless of whether the leading dirs are iCloud or mirror.
    """
    if not p:
        return p
    # Strip everything up to and including the rightmost `/Growth/`
    marker = "/Growth/"
    idx = p.rfind(marker)
    if idx >= 0:
        return p[idx + len(marker):]
    # Fallback: try canonical relative_to
    try:
        return str(Path(p).resolve().relative_to(GROWTH_DIR.resolve()))
    except (ValueError, OSError):
        return p


def render_dashboard(entities: list[dict], today: dt.date) -> list[str]:
    """Top-level at-a-glance state — replaces phase_status."""
    day = (today - PHASE_1_START).days + 1
    if day < 1:
        day = 1
    if day > PHASE_1_DAYS:
        day = PHASE_1_DAYS
    days_left = max(0, PHASE_1_DAYS - day)

    # Pull entity-set state
    exps = [e for e in entities if e["type"] == "experiment"]
    running = [e for e in exps if e["status"] == "running"]
    concluded = [e for e in exps if e["status"] in ("won", "killed", "inconclusive")]

    content = [e for e in entities if e["type"] == "content"]
    content_drafted = [e for e in content if e["status"] in ("drafted", "reviewed", "scheduled")]
    content_shipped = [e for e in content if e["status"] in ("published", "distributed")]

    bd = [e for e in entities if e["type"] == "bd_target"]
    bd_active = [e for e in bd if e["status"] in ("outreach", "engaged")]

    prospects = [e for e in entities if e["type"] == "prospect"]
    prospects_qualified_plus = [e for e in prospects if e["status"] in ("qualified", "scoped", "proposal-out", "won")]
    prospects_inbound = [e for e in prospects if e["status"] == "inbound"]

    launches = [e for e in entities if e["type"] == "launch"]
    launches_active = [e for e in launches if e["status"] in ("drafting", "ready", "scheduled")]

    metrics = [e for e in entities if e["type"] == "metric"]
    metrics_instrumented = [m for m in metrics if m["status"] in ("instrumented", "monitored")]
    metrics_red = [m for m in metrics if m["status"] == "not-instrumented"]

    open_decs = [e for e in entities if e["type"] == "decision" and e["status"] in ("open", "deferred")]
    open_decs_urgent = [
        e for e in open_decs
        if e.get("deadline") and parse_date(e.get("deadline"))
        and (parse_date(e.get("deadline")) - today).days <= 7
    ]

    projects = [e for e in entities if e["type"] == "project"]
    projects_red = [p for p in projects if (p.get("effective_rag") or "").lower() == "red"]
    projects_amber = [p for p in projects if (p.get("effective_rag") or "").lower() == "amber"]
    projects_green = [p for p in projects if (p.get("effective_rag") or "").lower() == "green"]

    nsm_lines = []
    for slug in ("wapw", "qpv"):
        m = next((mm for mm in metrics if mm["id"] == slug), None)
        if not m:
            continue
        title = m.get("title") or slug.upper()
        val = m.get("value")
        if val in (None, ""):
            nsm_lines.append(f"  {title[:48]:<48} ░░░░░░░░░░  NOT INSTRUMENTED")
        else:
            tgt = m.get("target") or "—"
            try:
                bar = _bar(float(val), float(tgt) if tgt not in (None, "—", "") else float(val) * 2)
            except (ValueError, TypeError):
                bar = "░" * 10
            nsm_lines.append(f"  {title[:48]:<48} {bar}  {val} / target {tgt}")

    lines = [
        "## ⚡ Dashboard",
        "",
        "```",
        f"  Phase 1 — Growth Program            {_bar(day, PHASE_1_DAYS)}  Day {day}/{PHASE_1_DAYS} · {days_left}d left",
        "",
        "  NORTH-STAR METRICS",
    ]
    if nsm_lines:
        lines.extend(nsm_lines)
    else:
        lines.append("    (no NSM entities found)")
    lines.append("")
    lines.append("  PIPELINE COUNTS                          ACTIVE       TOTAL")
    lines.append(f"  🤔 Open decisions                          {len(open_decs):<4}         {len(open_decs):<4}" + (f"  · ⚠ {len(open_decs_urgent)} urgent" if open_decs_urgent else ""))
    lines.append(f"  📋 Projects                                {len(projects) - len([p for p in projects if p['status'] in ('shipped', 'canceled', 'paused')]):<4}         {len(projects):<4}" + (f"  · 🔴 {len(projects_red)} red" if projects_red else "") + (f"  · 🟡 {len(projects_amber)} amber" if projects_amber else ""))
    lines.append(f"  🧪 Experiments                             {len(running):<4}         {len(exps):<4}" + (f"  · ✅ {len(concluded)} concluded" if concluded else ""))
    lines.append(f"  📝 Content (drafted+reviewed+scheduled)    {len(content_drafted):<4}         {len(content):<4}" + (f"  · ✅ {len(content_shipped)} shipped" if content_shipped else ""))
    lines.append(f"  🤝 BD (outreach+engaged)                   {len(bd_active):<4}         {len(bd):<4}")
    lines.append(f"  💼 Solutions (qualified+)                  {len(prospects_qualified_plus):<4}         {len(prospects):<4}" + (f"  · 📨 {len(prospects_inbound)} inbound" if prospects_inbound else ""))
    lines.append(f"  🚀 Launches                                {len(launches_active):<4}         {len(launches):<4}")
    lines.append(f"  📊 Metrics instrumented                    {len(metrics_instrumented):<4}         {len(metrics):<4}" + (f"  · 🔴 {len(metrics_red)} red" if metrics_red else ""))
    lines.append("```")
    lines.append("")
    # Red flags as a one-line callout
    flags = []
    if metrics_red:
        flags.append(f"{len(metrics_red)} metrics not instrumented (incl. {', '.join(m['id'] for m in metrics_red if m['id'] in ('wapw', 'qpv'))})")
    if open_decs_urgent:
        flags.append(f"{len(open_decs_urgent)} decision{'s' if len(open_decs_urgent) != 1 else ''} due in ≤7d")
    if projects_red:
        flags.append(f"{len(projects_red)} project{'s' if len(projects_red) != 1 else ''} red/blocked")
    if flags:
        lines.append(f"🚨 **Red flags.** {' · '.join(flags)}")
        lines.append("")
    return lines


def render_projects(entities: list[dict], today: dt.date) -> list[str]:
    """Project tracker — one row per cross-entity project."""
    projects = [e for e in entities if e["type"] == "project"]
    if not projects:
        return []

    # Sort: red first, then amber, then green, by deadline proximity within each band
    def _key(p):
        rag_order = {"red": 0, "amber": 1, "green": 2}
        rag = rag_order.get((p.get("effective_rag") or p.get("rag") or "").lower(), 3)
        td = p.get("target_date") or ""
        try:
            dl = dt.date.fromisoformat(td) if td else None
        except (ValueError, TypeError):
            dl = None
        deadline_sort = (dl - today).days if dl else 9999
        return (rag, deadline_sort, p.get("id") or "")
    projects.sort(key=_key)

    lines = ["## 📋 Projects — in flight", ""]
    active_projects = [p for p in projects if p["status"] not in ("shipped", "canceled", "paused")]
    inactive = [p for p in projects if p["status"] in ("shipped", "canceled", "paused")]
    lines.append(f"_{len(active_projects)} active · {len(inactive)} closed/paused_")
    lines.append("")
    lines.append("| RAG | Project | Owner | Target | Status | Progress | Blockers |")
    lines.append("|-----|---------|-------|--------|--------|----------|----------|")
    for p in active_projects:
        # Prefer auto-derived effective_rag; fall back to manual
        rag = (p.get("effective_rag") or p.get("rag") or "").lower()
        rag_icon = {"red": "🔴", "amber": "🟡", "green": "🟢"}.get(rag, "⚪")
        title = (p.get("title") or p.get("id") or "")[:65]
        owner = p.get("owner") or "—"
        target = p.get("target_date") or "—"
        status = p.get("status") or "—"
        prog = p.get("progress_pct")
        prog_str = f"{prog}%" if prog is not None else "—"
        blockers = p.get("blockers") or []
        blockers_n = len(blockers) if isinstance(blockers, list) else 0
        blockers_str = f"{blockers_n} 🚧" if blockers_n else "—"
        lines.append(f"| {rag_icon} | **{title}** | {owner} | {target} | `{status}` | {prog_str} | {blockers_str} |")
    lines.append("")
    # Per-project detail blocks for red/amber
    flagged = [
        p for p in active_projects
        if (p.get("effective_rag") or p.get("rag") or "").lower() in ("red", "amber")
    ]
    if flagged:
        lines.append("### Project detail (red / amber)")
        lines.append("")
        for p in flagged[:6]:
            title = p.get("title") or p["id"]
            rag = (p.get("effective_rag") or p.get("rag") or "").lower()
            rag_icon = {"red": "🔴", "amber": "🟡", "green": "🟢"}.get(rag, "⚪")
            target = p.get("target_date") or "no deadline"
            lines.append(f"**{rag_icon} {title}** — `{p['status']}` · target {target}")
            summary = p.get("status_summary")
            if summary:
                for s_line in str(summary).strip().splitlines():
                    lines.append(f"> {s_line}")
            # Auto-derived blockers (live state of linked entities)
            derived = p.get("derived_blockers") or []
            if isinstance(derived, list) and derived:
                lines.append("")
                lines.append("Auto-detected blockers (live):")
                for db in derived:
                    lines.append(f"- 🔴 {db}")
            blockers = p.get("blockers") or []
            if isinstance(blockers, list) and blockers:
                lines.append("")
                lines.append("Notes (manual):")
                for b in blockers:
                    lines.append(f"- 🚧 {b}")
            linked = p.get("linked_entities") or []
            if isinstance(linked, list) and linked:
                lines.append("")
                lines.append(f"Linked entities ({len(linked)}):")
                for le in linked[:5]:
                    lines.append(f"- `{le}`")
                if len(linked) > 5:
                    lines.append(f"- _+{len(linked) - 5} more_")
            lines.append("")
            lines.append("---")
            lines.append("")
    return lines


def render_phase_status(entities: list[dict], today: dt.date) -> list[str]:
    day = (today - PHASE_1_START).days + 1
    if day < 1:
        day = 1
    if day > PHASE_1_DAYS:
        day = PHASE_1_DAYS
    exps = [e for e in entities if e["type"] == "experiment"]
    running = [e for e in exps if e["status"] == "running"]
    concluded = [e for e in exps if e["status"] in ("won", "killed", "inconclusive")]
    metrics = [e for e in entities if e["type"] == "metric"]
    instrumented = [m for m in metrics if m["status"] in ("instrumented", "monitored")]

    nsm_lines = []
    for m in metrics:
        if (m.get("category") or "").lower() == "nsm" or (m.get("id") or "") in ("wapw", "qpv"):
            val = m.get("value")
            tgt = m.get("target")
            if val in (None, ""):
                bar = "░" * 10
                label = "not instrumented"
            else:
                try:
                    bar = _bar(float(val), float(tgt) if tgt not in (None, "") else float(val) * 2)
                except (ValueError, TypeError):
                    bar = "░" * 10
                label = f"{val}" + (f" / target {tgt}" if tgt not in (None, "") else "")
            nsm_lines.append(f"NSM {m.get('title') or m.get('id'):<24} {bar}  {label}")

    lines = ["## 📊 Where we are"]
    lines += [""]
    lines += ["```"]
    lines.append(f"Phase 1 progress  {_bar(day, PHASE_1_DAYS)}  Day {day}/{PHASE_1_DAYS}")
    lines.append(f"Experiments       {_bar(len(running), max(5, len(running) + len(concluded)))}  {len(running)} running · {len(concluded)} concluded · {len(exps)} total")
    if metrics:
        lines.append(f"Metric coverage   {_bar(len(instrumented), max(1, len(metrics)))}  {len(instrumented)}/{len(metrics)} instrumented")
    # Zergboard linkage coverage — non-workstream entities only (workstreams aren't card-backed)
    linkable = [e for e in entities if e["type"] != "workstream"]
    linked = [e for e in linkable if e.get("zergboard_card")]
    if linkable:
        lines.append(f"Zergboard linked  {_bar(len(linked), len(linkable))}  {len(linked)}/{len(linkable)} entities have cards")
    for n in nsm_lines:
        lines.append(n)
    lines += ["```", ""]
    return lines


def _section_table(rows: list[dict], cols: list[tuple[str, str, int]], empty_msg: str) -> list[str]:
    if not rows:
        return [f"_{empty_msg}_", ""]
    header = "| " + " | ".join(name for name, _, _ in cols) + " |"
    sep = "|" + "|".join("-" * (max(3, w + 2)) for _, _, w in cols) + "|"
    out = [header, sep]
    for r in rows:
        cells = []
        for _, key, _ in cols:
            v = r.get(key)
            cells.append(str(v) if v not in (None, "") else "—")
        out.append("| " + " | ".join(cells) + " |")
    out.append("")
    return out


def _counts(entities: list[dict], etype: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for e in entities:
        if e["type"] != etype:
            continue
        s = e.get("status") or "—"
        out[s] = out.get(s, 0) + 1
    return out


def _format_counts(counts: dict[str, int]) -> str:
    if not counts:
        return "none"
    return " · ".join(f"{v} {k}" for k, v in sorted(counts.items(), key=lambda x: -x[1]))


def render_experiments(entities: list[dict]) -> list[str]:
    exps = [e for e in entities if e["type"] == "experiment"]
    counts = _counts(entities, "experiment")
    lines = [f"## 🧪 Experiments ({_format_counts(counts)})", ""]
    running = [e for e in exps if e["status"] == "running"]
    rows_data = [
        {
            "id": e["id"],
            "title": (e.get("title") or "")[:60],
            "kill_date": e.get("kill_date") or "—",
            "phase": e.get("phase") or "—",
            "last_touch": e.get("last_touch") or "—",
        }
        for e in running
    ]
    lines += _section_table(
        rows_data,
        [("id", "id", 8), ("title", "title", 60), ("kill", "kill_date", 10), ("phase", "phase", 12), ("last", "last_touch", 10)],
        empty_msg="No experiments running.",
    )
    return lines


def render_content(entities: list[dict]) -> list[str]:
    counts = _counts(entities, "content")
    lines = [f"## 📝 Content ({_format_counts(counts)})", ""]
    active = [
        e for e in entities
        if e["type"] == "content" and e["status"] in ("drafted", "reviewed", "scheduled")
    ]
    rows_data = [
        {
            "id": e["id"],
            "title": (e.get("title") or "")[:60],
            "status": e["status"],
            "kind": e.get("kind") or "—",
            "scheduled": e.get("scheduled_date") or e.get("target_date") or "—",
        }
        for e in active
    ]
    lines += _section_table(
        rows_data,
        [("id", "id", 28), ("title", "title", 60), ("status", "status", 10), ("kind", "kind", 14), ("when", "scheduled", 10)],
        empty_msg="No in-flight content.",
    )
    return lines


def render_bd(entities: list[dict], today: dt.date) -> list[str]:
    bds = [e for e in entities if e["type"] == "bd_target"]
    counts = _counts(entities, "bd_target")
    stale = 0
    for e in bds:
        lt = parse_date(e.get("last_touch"))
        if lt and (today - lt).days > 14 and e["status"] in ("outreach", "engaged"):
            stale += 1
    lines = [f"## 🤝 BD ({_format_counts(counts)} · {stale} stale)", ""]
    active = [e for e in bds if e["status"] not in ("planned", "paused", "closed-won", "closed-lost")]
    rows_data = [
        {
            "id": e["id"],
            "title": (e.get("title") or "")[:40],
            "category": e.get("category") or "—",
            "status": e["status"],
            "last_touch": e.get("last_touch") or "—",
        }
        for e in active
    ]
    lines += _section_table(
        rows_data,
        [("id", "id", 24), ("title", "title", 40), ("category", "category", 14), ("status", "status", 10), ("last", "last_touch", 10)],
        empty_msg="No active BD conversations. (All targets in `planned` status.)",
    )
    return lines


def render_prospects(entities: list[dict]) -> list[str]:
    counts = _counts(entities, "prospect")
    lines = [f"## 💼 Solutions ({_format_counts(counts)})", ""]
    active = [e for e in entities if e["type"] == "prospect" and e["status"] in ("qualified", "scoped", "proposal-out")]
    rows_data = [
        {
            "id": e["id"],
            "company": e.get("company") or e.get("title") or e["id"],
            "status": e["status"],
            "score": e.get("score") or "—",
            "next": (e.get("next_action") or "")[:50],
        }
        for e in active
    ]
    lines += _section_table(
        rows_data,
        [("id", "id", 24), ("company", "company", 30), ("status", "status", 12), ("score", "score", 5), ("next", "next", 50)],
        empty_msg="No qualified+ prospects yet. (Inbound triage pending.)",
    )
    return lines


def render_launches(entities: list[dict]) -> list[str]:
    counts = _counts(entities, "launch")
    lines = [f"## 🚀 Launches ({_format_counts(counts)})", ""]
    active = [e for e in entities if e["type"] == "launch" and e["status"] in ("drafting", "ready", "scheduled")]
    rows_data = [
        {
            "id": e["id"],
            "title": (e.get("title") or "")[:50],
            "status": e["status"],
            "ship": e.get("ship_date") or "—",
        }
        for e in active
    ]
    lines += _section_table(
        rows_data,
        [("id", "id", 24), ("title", "title", 50), ("status", "status", 12), ("ship", "ship", 12)],
        empty_msg="No launches in progress.",
    )
    return lines


def render_themes(entities: list[dict]) -> list[str]:
    counts = _counts(entities, "theme")
    return [f"## 🧭 Themes ({_format_counts(counts)})", "", "_See `themes/` for per-theme detail._", ""]


def render_workstreams(entities: list[dict]) -> list[str]:
    counts = _counts(entities, "workstream")
    return [f"## 🧱 Workstreams ({_format_counts(counts)})", "", "_Cross-links to `~/.claude/workstreams/state.json`._", ""]


def render_dogfood(entities: list[dict]) -> list[str]:
    return [
        "## 🐕 Dogfood",
        "",
        "_See `dogfood/_active.txt` for the currently-active product slug and `dogfood/<slug>-walkthrough.md` per-product logs. Managed by `dogfood-walkthrough` skill (genre-relaxed; no envelope)._",
        "",
    ]


def render_measurement(entities: list[dict]) -> list[str]:
    return [
        "## 📐 Measurement",
        "",
        "_See `measurement/<slug>.yaml` for per-product Zergalytics specs. Consumed by `funnel-analyzer`, `growth-dashboard` (lines 1-4, 7-11), `utm-attribution` (allowlist), `launch-ops` (kill_readiness_gate). Template at `measurement/_template.yaml` (genre-relaxed; no envelope)._",
        "",
    ]


def render_crosslinks() -> list[str]:
    return [
        "## 🔗 Related",
        "",
        "- `Marketing/` — PMM briefs, sales enablement, email lifecycle (not owned by hub this phase)",
        "- `Writing/Launches/` — launch announcement drafts",
        "- `weekly/` — historical weekly dashboard snapshots",
        "- `_meta/schema.md` — frontmatter contract",
        "- `_meta/index.json` — flat cross-entity index",
        "- `_meta/decisions.json` — full action queue",
        "",
    ]


def render(index_payload: dict, decisions_payload: dict) -> str:
    today = dt.date.today()
    entities = index_payload.get("entities", [])
    decisions = decisions_payload.get("decisions", [])
    config = load_config()
    decisions_limit = config.get("decisions", {}).get("visible_count", DECISIONS_VISIBLE_DEFAULT)
    hide_healthy = bool(config.get("hide_healthy_sections", True))

    section_renderers = {
        "dashboard": lambda: render_dashboard(entities, today),
        "open_decisions": lambda: render_open_decisions(entities, today),
        "projects": lambda: render_projects(entities, today),
        "decisions": lambda: render_decisions(decisions, limit=decisions_limit),
        "debt": lambda: render_debt(decisions),
        "phase_status": lambda: render_phase_status(entities, today),
        "experiments": lambda: render_experiments(entities),
        "content": lambda: render_content(entities),
        "bd": lambda: render_bd(entities, today),
        "prospects": lambda: render_prospects(entities),
        "launches": lambda: render_launches(entities),
        "themes": lambda: render_themes(entities),
        "workstreams": lambda: render_workstreams(entities),
        "dogfood": lambda: render_dogfood(entities),
        "measurement": lambda: render_measurement(entities),
        "crosslinks": lambda: render_crosslinks(),
    }

    # Hide healthy: drop a section if its entity_type has zero non-planned entities.
    # (Crosslinks and decisions/phase_status are never hidden.)
    healthy_check_type = {
        "experiments": "experiment",
        "content": "content",
        "publishing": "publishing",
        "bd": "bd_target",
        "prospects": "prospect",
        "launches": "launch",
        "themes": "theme",
        "workstreams": "workstream",
    }
    inactive_status = {
        "experiment": {"won", "killed", "inconclusive"},
        "content": {"published", "distributed", "parked"},
        "publishing": {"published", "distributed", "archived"},
        "bd_target": {"planned", "paused", "closed-won", "closed-lost"},
        "prospect": {"won", "lost"},
        "launch": {"shipped", "parked"},
        "theme": {"retired"},
        "workstream": {"parked", "stale"},
    }

    parts: list[str] = []
    parts += render_header(today)
    for section in config.get("sections", DEFAULT_CONFIG["sections"]):
        renderer = section_renderers.get(section)
        if not renderer:
            continue
        if hide_healthy and section in healthy_check_type:
            etype = healthy_check_type[section]
            active = [
                e for e in entities
                if e["type"] == etype and e.get("status") not in inactive_status.get(etype, set())
            ]
            if not active:
                continue
        parts += renderer()
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    # Resolve index/decisions via staging→iCloud→mirror cascade so this
    # works under launchd TCC immediately after index.py + decisions.py
    # stage their fresh outputs.
    idx_text = read_growth_file("_meta/index.json")
    if idx_text is None:
        print("missing _meta/index.json — run `gtm-hub regenerate` first", file=sys.stderr)
        return 1
    idx = json.loads(idx_text)
    dec_text = read_growth_file("_meta/decisions.json")
    dec = json.loads(dec_text) if dec_text else {"decisions": []}
    content = render(idx, dec)
    # Only write if changed
    existing = read_growth_file("README.md")
    if existing == content:
        print(f"unchanged: README.md")
        return 0
    written = write_growth_file("README.md", content)
    print(f"wrote {written} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
