"""Multi-provider image generation with quota fallback chain.

Order: nano-banana-pro (Gemini 3 Pro Image) → fal-image-skill (Flux Pro) → Pollinations (free).
On quota failure, falls through to the next provider transparently.
On all-providers-failed, queues the prompt to /tmp/blog-imagery/queue/<slug>.json.
"""
from __future__ import annotations

import json
import subprocess
import time
import urllib.parse
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

NANO_BIN = Path.home() / ".claude" / "skills" / "nano-banana-pro" / "generate_image.py"
FAL_BIN = Path.home() / ".claude" / "skills" / "fal-image-skill" / "fal_image_skill.py"

QUEUE_DIR = Path("/tmp/blog-imagery/queue")
QUEUE_DIR.mkdir(parents=True, exist_ok=True)

# Aspect → (nano-banana --aspect, target dimensions)
ASPECT_MAP = {
    "1.91:1": ("16:9", (1200, 630)),  # OG card; closest nano-banana ratio is 16:9
    "16:9":   ("16:9", (1200, 675)),
    "1:1":    ("1:1",  (1200, 1200)),
    "3:2":    ("16:9", (1200, 800)),  # closest available
}


@dataclass
class GenResult:
    success: bool
    path: Optional[Path] = None
    provider: str = ""
    error: str = ""


def try_nano_banana(prompt: str, aspect: str, out_path: Path) -> GenResult:
    """Try Gemini 3 Pro Image via nano-banana-pro skill."""
    if not NANO_BIN.exists():
        return GenResult(False, error="nano-banana-pro skill not found")
    nano_aspect, _ = ASPECT_MAP.get(aspect, ("16:9", (1200, 630)))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_dir = out_path.parent
    try:
        res = subprocess.run(
            ["python3", str(NANO_BIN), prompt,
             "--aspect", nano_aspect,
             "--resolution", "2K",
             "--output", str(tmp_dir),
             "--no-text"],
            capture_output=True, text=True, timeout=180,
        )
        if res.returncode != 0:
            return GenResult(False, provider="nano-banana", error=res.stderr.strip()[:300])
        # Script writes a timestamp_prompt.png file. Find the newest png in tmp_dir matching pattern.
        candidates = sorted(tmp_dir.glob("*.png"), key=lambda p: p.stat().st_mtime, reverse=True)
        # Filter out the explicit out_path and known long-lived hero filenames.
        for c in candidates:
            if c == out_path or "_" in c.name and len(c.name) > 30:
                # Likely nano-banana's autogenerated timestamp_prompt name
                c.rename(out_path)
                return GenResult(True, path=out_path, provider="nano-banana")
        # Stdout contains the path on success. Try to find it.
        for line in res.stdout.splitlines():
            line = line.strip()
            if line.endswith(".png") and Path(line).exists():
                Path(line).rename(out_path)
                return GenResult(True, path=out_path, provider="nano-banana")
        return GenResult(False, provider="nano-banana", error="output file not located")
    except subprocess.TimeoutExpired:
        return GenResult(False, provider="nano-banana", error="timeout")
    except Exception as e:
        return GenResult(False, provider="nano-banana", error=str(e)[:300])


def try_fal(prompt: str, aspect: str, out_path: Path) -> GenResult:
    """Try Flux via fal-image-skill (CLI: `gen <prompt> -m flux-pro -a <aspect> -o <path>`)."""
    if not FAL_BIN.exists():
        return GenResult(False, error="fal-image-skill not found")
    fal_aspect = {"1.91:1": "16:9", "16:9": "16:9", "1:1": "1:1", "3:2": "16:9"}.get(aspect, "16:9")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        res = subprocess.run(
            ["python3", str(FAL_BIN), "gen", prompt,
             "-m", "flux-pro",
             "-a", fal_aspect,
             "-o", str(out_path)],
            capture_output=True, text=True, timeout=180,
        )
        if res.returncode != 0:
            return GenResult(False, provider="fal", error=res.stderr.strip()[:300])
        if out_path.exists() and out_path.stat().st_size > 5000:
            return GenResult(True, path=out_path, provider="fal")
        return GenResult(False, provider="fal", error=f"output too small ({out_path.stat().st_size if out_path.exists() else 0} bytes)")
    except subprocess.TimeoutExpired:
        return GenResult(False, provider="fal", error="timeout")
    except Exception as e:
        return GenResult(False, provider="fal", error=str(e)[:300])


POLLINATIONS_BRAND_SUFFIX = " Dark cosmic background, electric blue + amber accents, abstract conceptual art, no text, no letters."


def try_pollinations(prompt: str, aspect: str, out_path: Path) -> GenResult:
    """Try Pollinations (free, JPEG-as-PNG, lower quality).

    Pollinations URLs have a hard length limit. Strip the long brand anchor and
    use a compact pollinations-specific suffix so the meaningful concept survives
    URL-encoding intact.
    """
    _, (w, h) = ASPECT_MAP.get(aspect, ("16:9", (1200, 630)))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    # Strip the brand anchor section if it's there (it starts with "Aesthetic:").
    if "Aesthetic:" in prompt:
        concept = prompt.split("Aesthetic:")[0].strip()
    else:
        concept = prompt
    short_prompt = (concept[:380].rsplit(".", 1)[0] + ".") + POLLINATIONS_BRAND_SUFFIX
    enc = urllib.parse.quote(short_prompt)
    url = f"https://image.pollinations.ai/prompt/{enc}?width={w}&height={h}&nologo=true&model=flux"
    try:
        res = subprocess.run(
            ["curl", "-sSL", "--max-time", "60", url, "-o", str(out_path)],
            capture_output=True, text=True, timeout=90,
        )
        if res.returncode != 0:
            return GenResult(False, provider="pollinations", error=res.stderr.strip()[:200])
        if out_path.exists() and out_path.stat().st_size > 5000:
            return GenResult(True, path=out_path, provider="pollinations")
        return GenResult(False, provider="pollinations", error=f"output too small ({out_path.stat().st_size if out_path.exists() else 0} bytes)")
    except Exception as e:
        return GenResult(False, provider="pollinations", error=str(e)[:200])


def queue_prompt(slug: str, label: str, prompt: str, aspect: str, target_path: Path) -> Path:
    """When all providers fail, save the prompt for later retry."""
    queue_path = QUEUE_DIR / f"{slug}-{label}.json"
    queue_path.write_text(json.dumps({
        "slug": slug,
        "label": label,
        "prompt": prompt,
        "aspect": aspect,
        "target_path": str(target_path),
        "queued_at": time.time(),
    }, indent=2))
    return queue_path


def generate(prompt: str, aspect: str, out_path: Path, slug: str = "", label: str = "",
             provider: str = "auto") -> GenResult:
    """Generate one image with provider fallback. Queues on full failure."""
    chain = []
    if provider == "auto":
        chain = [try_nano_banana, try_fal, try_pollinations]
    elif provider == "nano-banana":
        chain = [try_nano_banana]
    elif provider == "fal":
        chain = [try_fal]
    elif provider == "pollinations":
        chain = [try_pollinations]
    else:
        return GenResult(False, error=f"unknown provider: {provider}")

    last_err = ""
    for fn in chain:
        result = fn(prompt, aspect, out_path)
        if result.success:
            return result
        last_err = f"[{result.provider}] {result.error}"
        print(f"  ⚠ {last_err}", flush=True)

    # All failed — queue for retry.
    if slug and label:
        queued = queue_prompt(slug, label, prompt, aspect, out_path)
        print(f"  → queued to {queued} for later retry", flush=True)
    return GenResult(False, provider="all", error=last_err)
