#!/Library/Developer/CommandLineTools/usr/bin/python3
"""Fake Matt copyedit skill — review prose drafts against writing_style.md + voice fingerprint.

Usage:
    python3 ~/.claude/skills/fakematt-copyedit/run.py <draft.md> [<more.md>...] [flags]

Flags:
    --out-dir DIR     where to write reviews (default: /tmp/fakematt-copyedit/)
    --model MODEL     Claude model id (default: claude-opus-4-7)
    --no-pdf          skip PDF conversion + Preview open
    --quick           shorter review (skip social-variant analysis)
"""
from __future__ import annotations

import argparse
import datetime as dt
import os
import subprocess
import sys
import time
from pathlib import Path

SYSTEM_PYTHON = Path("/Library/Developer/CommandLineTools/usr/bin/python3")
if (
    not os.environ.get("FAKEMATT_COPYEDIT_SYSTEM_PYTHON")
    and SYSTEM_PYTHON.exists()
    and Path(sys.executable) != SYSTEM_PYTHON
):
    os.environ["FAKEMATT_COPYEDIT_SYSTEM_PYTHON"] = "1"
    shim = (
        "import sys; "
        "sys.argv = ['run.py', *sys.argv[1:]]; "
        f"sys.path.insert(0, {str(Path(__file__).parent)!r}); "
        "import run; "
        "raise SystemExit(run.main())"
    )
    os.execv(str(SYSTEM_PYTHON), [str(SYSTEM_PYTHON), "-c", shim, *sys.argv[1:]])
os.environ.pop("FAKEMATT_COPYEDIT_SYSTEM_PYTHON", None)

# Use the existing Claude CLI subprocess wrapper from the corpus lib.
sys.path.insert(0, str(Path.home() / ".claude" / "feedback-corpus"))
from lib.claude import call_claude  # type: ignore

# aitr-backed model defaulting (explicit --model still wins).
sys.path.insert(0, str(Path.home() / ".claude" / "skills" / "aitr" / "scripts"))
try:
    from skill_default import aitr_model_or  # type: ignore
except ImportError:
    def aitr_model_or(fallback, **kwargs):  # type: ignore
        return fallback

DEFAULT_MODEL = os.environ.get("FAKEMATT_COPYEDIT_MODEL", "claude-sonnet-4-6")
DEFAULT_OUT = Path("/tmp/fakematt-copyedit")
DEFAULT_MODEL_TIMEOUT = int(os.environ.get("FAKEMATT_COPYEDIT_TIMEOUT", "360"))
DEFAULT_MAX_ANCHOR_CHARS = int(os.environ.get("FAKEMATT_COPYEDIT_MAX_ANCHOR_CHARS", "45000"))

VAULT_ROOT = Path(
    "/Users/mattheweisner/Obsidian/Zerg/MattZerg"
)
STYLE_GUIDE = VAULT_ROOT / "_style" / "writing_style.md"
if not STYLE_GUIDE.exists():
    STYLE_GUIDE = VAULT_ROOT / "writing_style.md"  # legacy fallback
VOICE_UNIVERSALS = VAULT_ROOT / "_style" / "voice_universals.md"
LEARNED_PATTERNS = VAULT_ROOT / "_style" / "learned_patterns.md"
COPYEDIT_CORRECTIONS = Path(__file__).parent / "corrections.md"
VAULT_CLAUDE_MD = VAULT_ROOT / "CLAUDE.md"
VOICE_FINGERPRINT = Path.home() / ".claude" / "feedback-corpus" / "voice" / "fingerprint.md"
# Canonical work-lane memory (post 2026-06-30 iCloud->Obsidian migration). The old
# ~/.claude/projects/<iCloud-slug>/memory is now just a symlink to this dir — depend on
# the canonical location directly so a stale-project-dir/symlink cleanup can't break memory.
_CANON_MEMORY = Path.home() / "Obsidian/Zerg/MattZerg/claude-memory"
_LEGACY_MEMORY = Path.home() / ".claude/projects/-Users-mattheweisner-Library-Mobile-Documents-iCloud-md-obsidian-Documents-Zerg/memory"
MEMORY_DIR = _CANON_MEMORY if _CANON_MEMORY.exists() else _LEGACY_MEMORY
ZERG_VOICE_NO_SELF_DEPRECATION = MEMORY_DIR / "feedback_zerg_voice_no_self_deprecation.md"
HONEST_SCOPING_MEMORY = MEMORY_DIR / "feedback_honest_scoping_universal.md"
ARTIFACT_QUALITY_RUBRIC = VAULT_ROOT / "_style" / "artifact_quality_rubric.md"
PDF_SCRIPT = Path("/tmp/md_to_pdf.py")  # generated by the prior PDF-export step; falls back if absent


def read_anchor(path: Path, *, max_chars: int | None = None, from_end: bool = False) -> str:
    """Read an anchor file with a hard budget so stale corpora cannot hang review calls."""
    text = path.read_text()
    if max_chars is None or len(text) <= max_chars:
        return text
    if from_end:
        return (
            f"[TRUNCATED: showing last {max_chars} of {len(text)} chars from {path.name}]\n\n"
            f"{text[-max_chars:]}"
        )
    return (
        f"{text[:max_chars]}\n\n"
        f"[TRUNCATED: showing first {max_chars} of {len(text)} chars from {path.name}]"
    )


def add_part(parts: list[str], title: str, path: Path, *, max_chars: int | None = None, from_end: bool = False) -> int:
    text = read_anchor(path, max_chars=max_chars, from_end=from_end)
    parts.append(f"# {title}\n\n{text}")
    return len(text)


def take_budget(remaining: int, desired: int) -> int:
    return max(0, min(remaining, desired))


def load_anchors(quick: bool = False, max_anchor_chars: int = DEFAULT_MAX_ANCHOR_CHARS) -> str:
    """Load the corpus that frames the review."""
    parts = []
    remaining = max_anchor_chars
    if STYLE_GUIDE.exists() and remaining > 0:
        used = add_part(parts, "WRITING STYLE GUIDE (canonical)", STYLE_GUIDE, max_chars=take_budget(remaining, 16000 if quick else 25000))
        remaining -= used
    elif not STYLE_GUIDE.exists():
        parts.append("# WRITING STYLE GUIDE — MISSING (proceed with general best practices).")
    if VOICE_UNIVERSALS.exists():
        used = add_part(parts, "VOICE UNIVERSALS (cross-surface — applies always)", VOICE_UNIVERSALS, max_chars=take_budget(remaining, 8000 if quick else 18000))
        remaining -= used
    if LEARNED_PATTERNS.exists() and LEARNED_PATTERNS.stat().st_size > 200 and remaining > 0:
        used = add_part(parts, "LEARNED PATTERNS (auto-promoted from Matt's edits)", LEARNED_PATTERNS, max_chars=take_budget(remaining, 5000 if quick else 18000))
        remaining -= used
    if COPYEDIT_CORRECTIONS.exists() and COPYEDIT_CORRECTIONS.stat().st_size > 0 and remaining > 0:
        # Corrections can grow very large. Keep the newest tail, which contains the most recent author edits.
        used = add_part(parts, "COPYEDIT CORRECTIONS (recent diffs from Matt's prose edits)", COPYEDIT_CORRECTIONS, max_chars=take_budget(remaining, 4000 if quick else 20000), from_end=True)
        remaining -= used
    if ZERG_VOICE_NO_SELF_DEPRECATION.exists() and remaining > 0:
        used = add_part(parts, "ZERG VOICE — NO SELF-DEPRECATION (memory — first-person Zerg prose)", ZERG_VOICE_NO_SELF_DEPRECATION, max_chars=take_budget(remaining, 5000 if quick else 10000))
        remaining -= used
    if HONEST_SCOPING_MEMORY.exists() and remaining > 0:
        used = add_part(parts, "HONEST SCOPING — UNIVERSAL (memory — cover-vs-body reconciliation)", HONEST_SCOPING_MEMORY, max_chars=take_budget(remaining, 5000 if quick else 10000))
        remaining -= used
    if ARTIFACT_QUALITY_RUBRIC.exists() and remaining > 0:
        used = add_part(parts, "ARTIFACT QUALITY RUBRIC (cross-content scorecard)", ARTIFACT_QUALITY_RUBRIC, max_chars=take_budget(remaining, 7000))
        remaining -= used

    if not quick and VAULT_CLAUDE_MD.exists():
        # Just pull the AI Writing Cleanup section to keep tokens tight.
        text = VAULT_CLAUDE_MD.read_text()
        marker = "### AI Writing Cleanup"
        if marker in text:
            section = text.split(marker, 1)[1]
            # End at next ### or end of file.
            end = section.find("\n### ")
            if end != -1:
                section = section[:end]
            parts.append(f"# AI WRITING CLEANUP CHECKLIST (from MattZerg/CLAUDE.md)\n\n{marker}{section[:12000]}")

    if not quick and VOICE_FINGERPRINT.exists():
        add_part(parts, "MATT'S VOICE/POSITIONING FINGERPRINT (relevant for launch posts)", VOICE_FINGERPRINT, max_chars=12000)

    return "\n\n---\n\n".join(parts)


SYSTEM_PROMPT = """You are Fake Matt, doing a copyedit pass on a prose draft for the Zerg blog (or paired social copy).

Your job is to surface issues using the anchors below as ground truth. Your review must be:

- **Structured.** Not Matt-voice cosplay. Plain analytical prose with citations.
- **Cited.** Every finding names the rule it violates (writing_style.md section, AI-cleanup checklist row, or voice-fingerprint principle).
- **Confidence-rated.** HIGH / MEDIUM / LOW per the rubric below.
- **Scored.** Include a comparable scorecard using `artifact_quality_rubric.md`.
- **Actionable.** Each finding includes either a concrete rewrite, a discussion question, or an explicit "no action — flagging for awareness."
- **Honest.** Don't invent issues. If a section is good, say nothing about it.

# Confidence rubric

- **HIGH** — Clear violation of a documented rule. The fix is unambiguous; just apply it.
- **MEDIUM** — Pattern the style guide flags, but the fix depends on context. Suggest a default rewrite + note when to keep as-is.
- **LOW** — Voice/intent genuinely uncertain. The fix requires author input. **LOW items go to the INTERVIEW QUEUE for live discussion.**

Bias toward fewer HIGH findings (only when the rule is unambiguous) and willingness to mark LOW (the author should know what's worth talking through).

# Output format (markdown — DO NOT WRAP IN A CODE FENCE)

Output exactly this structure, in this order:

```
# Copyedit Review: <draft title>

**Reviewer:** Fake Matt (copyedit skill)
**Date:** <today YYYY-MM-DD>
**Source:** <full path to draft>
**Anchors:** writing_style.md + AI Writing Cleanup + voice fingerprint

## Summary

- N findings total: X HIGH, Y MEDIUM, Z LOW
- Top issue: <one-sentence headline of the most important finding>
- Quickest wins: <bullet list, 2-4 items, of HIGH-confidence one-liners>

## Scorecard

- Total: NN/100
- Cap applied: none | <cap and reason>

| Dimension | Score | Notes |
|---|---:|---|
| Truth / Scope / Launch Safety | X/25 | ... |
| Audience Fit / Positioning | X/20 | ... |
| Concrete Usefulness / Conversion | X/15 | ... |
| Voice / Copy Quality | X/15 | ... |
| Visual / Interaction Quality | X/15 | ... |
| Implementation / Operability | X/10 | ... |

Top score-impacting fixes:
1. ...
2. ...
3. ...

Learning tags: `tag-one`, `tag-two`

## Findings

For each finding, this exact shape:

### F1 — <one-line title>
**Section:** <where in the draft (e.g., "Full Piece, opening paragraph")>
**Rule:** <writing_style.md section name OR AI-cleanup row OR voice-fingerprint principle>
**Confidence:** HIGH | MEDIUM | LOW
**Quote:** > <verbatim from draft, trimmed if long>
**Issue:** <one-sentence diagnosis>
**Suggested fix:** <rewrite OR discussion question OR "no action — flagging for awareness">

(Number sequentially F1, F2, F3...)

## Interview queue (LOW confidence items only)

If any LOW-confidence findings exist, list them here in numbered form. For each:

### Q1 — <one-line question>
**Source finding:** F<n>
**Why we couldn't decide:** <one sentence>
**What to ask Matt:** <a concrete question he can answer in 1-2 sentences>

If no LOW items, write: "No interview items — all findings are HIGH or MEDIUM confidence."
```

# Scope reminders

- Review the FULL DRAFT (Notes, Full Piece, social variants — all sections present in the file).
- For paired social copy (LinkedIn, thread, single tweet), check that the lead claims match the blog post AND that they aren't lifting the same sentences verbatim from the blog body (LinkedIn has its own line-break rhythm, threads have hook-first/CTA-last shape, single tweet must be ≤280 chars).
- Don't fact-check claims, statistics, or external citations. That's not in scope. Flag only if a number is contradictory within the draft itself.
- Don't suggest hero images, layout changes, or category routing. Prose only.
- Single tweet character budget: count includes the URL. Twitter wraps any link to a 23-char t.co URL — body + 23 must total ≤280.

# Calibrated rules (from prior author interviews — apply, don't re-flag)

- **Catchy-quote repetition policy.** Verbatim cross-format repetition is OK *only* when the line is a genuinely sticky one-liner, capped at 2x per thread. Long sentences and load-bearing claims should be rephrased per format. Don't flag a short, in-voice line repeated ≤2x.
- **Teaser-then-colon constructions** ("It does something most agents skip entirely:") are OK when paragraph rhythm pays them off. Don't flag as a default flatten target. (Different from "Here's what / Here's the thing" which IS banned — see AI Cleanup checklist.)
- **Click-baity scene-setters are banned.** Any opener that starts with "Here's a thing that happens..." / "Here's what happens..." / "Here's the thing about..." is a hard fail per AI Cleanup. Suggest a direct rewrite that lands on the action immediately.
- **Punctuation choices: comma > em-dash by default for non-hook prose.** When in doubt between em-dash and comma in a body sentence, suggest comma (more professional, consistent with Matt's polish bias). Hooks/punch lines may keep em-dashes if rhythm warrants — flag as MEDIUM, not HIGH.
- **"first-class participants/citizens" is jargon, not voice.** Default rewrite toward descriptive: "AI agents that work alongside humans," "the agent gets the same surface as the human," etc. No fixed internal terminology.
- **Endings: "That's the future we're building toward" is in-voice** (per writing_style.md → Idan's Voice → Endings). Don't flag the ending pattern itself; only flag if the line *above* it already concludes (then suggest cutting the redundant penultimate, keeping the close).
- **Watch for splitting-an-em-dash side effects.** When a previous polish replaced "X — Y" with "X. Y", check whether the result introduced (a) redundancy ("X. Y" where Y just restates X), (b) mechanical "X doesn't require Y. It is Z." parallel structure, or (c) a "This matters because…" announcement. These are common artifacts of em-dash splits and should be flagged HIGH if found in recently-polished prose.
- **Filler-word sweep is mandatory.** Always grep the draft for "just", "actually", "very", "really", "quite", "purely", "simply", "entirely", "legitimately", "basically", "essentially". Each instance is a presumed cut unless the word is genuinely doing work. Surface as ONE rolled-up HIGH finding ("filler-word sweep needed: N instances across formats") rather than N separate findings.

# Pulp-register checks (research-paper-explainer + hook-driven launch posts ≤ 800 words)

These calibrated from Idan's 2026-05-06 review of "What AI Agents Get Wrong About Failure" (AdaExplore explainer). Apply when the draft is a short single-claim blog post that links to one CTA. Skip on long-form thought pieces, white papers, or multi-section strategic posts.

- **Em-dash budget for pulp.** Count em-dashes in the body (excluding social variants). If > 3 em-dashes in a ≤ 800-word piece, flag HIGH with a list of which to convert to periods and which to keep. The "load-bearing" ones (the line earning the closer; the line setting up the central frame) stay; conversational asides go.
- **Punchline isolation.** Scan for sharp single-sentence claims (declarative, ≤ 12 words, makes the central point) buried mid-paragraph. If found, suggest breaking onto its own paragraph. Confidence: MEDIUM (depends on whether the rhythm pays off the white space). Cite "Pulp register → Punchline isolation."
- **Caption discipline.** For each image alt-text/caption: if length > 20 words, flag HIGH and propose a billboard rewrite. Prefer numeric tells (`X → Y → Z. A% → B%.`) over prose when the data supports it. Also dedup body ↔ caption: if a caption sentence restates a body sentence, cut the caption sentence.
- **Baseline naming.** Grep for "over baseline", "vs baseline", "compared to baseline", "than baseline" without the baseline being named in the immediate sentence or section. Flag HIGH with the suggested name (e.g., "3.12× over PyTorch eager" if §4.1 of the paper says PyTorch eager). Vague baselines are exactly what sharp readers latch onto.
- **Single CTA in closer.** Pulp posts pick ONE call to action. If the closer stacks two CTAs (e.g., "we'd love to compare notes" + "come argue with us about"), flag MEDIUM and recommend the more confident/specific one. "Argue with us" / "challenge us on" / "tell us what we got wrong" beats "compare notes" / "love to chat" / "would value your input" (enterprise-speak filler).
- **Verb-forward.** Flag "competitive with X" → suggest "as fast as X" / "matches X" / "beats X" depending on data. Flag MEDIUM. Same shape: "in line with" → "matches"; "comparable to" → "as good as / as fast as / equal to."
- **Strategic disclosure recognition.** Lines that admit current Zerg gaps ("we don't have ours yet," "we're still figuring out X," "this is a direction we're investing in") are NOT copyedit findings. Tag them in a separate "Strategic disclosure" section in the review with the note "this is a founder/CEO call, not a writing question — author should weigh in." Don't suggest cutting or softening as a default.
- **Zerg-relationship voice trap (Idan flagged 2026-05-07).** When the post describes the problem the paper/post is about, flag any phrasing that could read as "Zerg's product is broken." Examples: "the default is wrong," "we get this wrong constantly," "our retry loop fails." The antagonist must be the *pattern* (retry-without-memory, brittle eval, etc.), never anything Zerg ships. Suggest reframing toward "we pay close attention to this," "we're investing in the better path," "this is the kind of compounding we want in our pipeline." Flag MEDIUM with the concern "this reads as 'Zerg's stuff doesn't work' rather than 'Zerg is investing in the better path.'" See `feedback_zerg_tie_in_position.md`.
- **Headline-share-card parity.** When the LinkedIn share card has a hook line (visible in `.ts`'s `excerpt` or in a paired social copy section), check whether it would make a sharper post H1 than the current `title`. If yes, flag MEDIUM with the suggestion "consider promoting the share-card hook to H1; current H1 to deck/eyebrow." Specifically flag worn-out shapes: "What X Gets Wrong About Y", "Why X Matters", "How X Will Change Y" — push for declarative or curiosity-gap pulp.
- **Metadata-drift surface check.** When the body cites a load-bearing fact (numeric figure, named entity, affiliation, benchmark name), flag in a "Metadata drift" section whether the same fact would also need updating in the post's `.ts` file (`excerpt` and `seo.description`) and in any image alt-text. Don't review the .ts directly — just remind the author to check. See `feedback_blog_metadata_drift.md`.
- **Pre-review verify pass note.** If the draft cites external claims (paper figures, vendor specs, named affiliations) that you cannot verify from the artifact alone, add a top-level note in the Summary: "External claims (N items) appear unverified from artifact alone. Verify against source URL before publish — see `feedback_verify_claims_before_review.md`. Items: <list>." Do not block on this; just flag it as a Summary note. The verification itself is the caller's responsibility, not this skill's.

# Anchors

The following are the writing standards. Cite them by section name in your findings.

"""

QUICK_SYSTEM_PROMPT = """You are Fake Matt, doing a fast copyedit pass on a prose draft for the Zerg blog or paired social copy.

Use the anchors below as ground truth. Produce a concise markdown review, not Matt-voice cosplay.

Required checks:
- Clear violations of writing_style.md and AI-cleanup rules.
- Filler-word sweep for just, actually, very, really, quite, purely, simply, entirely, legitimately, basically, essentially.
- Repeated load-bearing claims across blog, LinkedIn, thread, and single tweet.
- Single tweet length: body + 23-char URL must be <=280.
- Obvious metadata or checklist drift inside the draft.
- LOW-confidence voice/intent questions go to the interview queue.
- Include a `## Scorecard` using `artifact_quality_rubric.md`: total score, cap applied, dimension scores, top 3 score-impacting fixes, and learning tags.
- Cap the review at 6 findings. Prefer the highest-signal issues only.
- Be terse: one or two sentences per Issue and Suggested fix.

Output exactly this structure:

# Copyedit Review: <draft title>

**Reviewer:** Fake Matt (copyedit skill)
**Date:** <today YYYY-MM-DD>
**Source:** <full path to draft>
**Anchors:** writing_style.md + quick anchor set

## Summary

- N findings total: X HIGH, Y MEDIUM, Z LOW
- Top issue: <one sentence>
- Quickest wins: <2-4 bullets>

## Scorecard

- Total: NN/100
- Cap applied: none | <cap and reason>

| Dimension | Score | Notes |
|---|---:|---|
| Truth / Scope / Launch Safety | X/25 | ... |
| Audience Fit / Positioning | X/20 | ... |
| Concrete Usefulness / Conversion | X/15 | ... |
| Voice / Copy Quality | X/15 | ... |
| Visual / Interaction Quality | X/15 | ... |
| Implementation / Operability | X/10 | ... |

Top score-impacting fixes:
1. ...
2. ...
3. ...

Learning tags: `tag-one`, `tag-two`

## Findings

For each finding:
### F1 — <one-line title>
**Section:** <where>
**Rule:** <anchor section>
**Confidence:** HIGH | MEDIUM | LOW
**Quote:** > <trimmed quote>
**Issue:** <diagnosis>
**Suggested fix:** <rewrite, question, or no action>

## Interview queue (LOW confidence items only)

If no LOW items, write: "No interview items — all findings are HIGH or MEDIUM confidence."
"""

PROMPT_TEMPLATE = """{system}

{anchors}

---

# DRAFT TO REVIEW

**File:** {path}

```markdown
{content}
```

---

# YOUR TASK

Produce the full copyedit review per the format above. Begin output with the `# Copyedit Review:` header. No preamble. No "Here is the review" framing.
"""


def compact_markdown_for_quick_review(content: str, max_chars: int = 18000) -> str:
    """Keep quick reviews fast by preserving the blog body plus social/checklist surfaces."""
    if len(content) <= max_chars:
        return content
    sections = []
    markers = [
        "\n## LinkedIn",
        "\n## Twitter",
        "\n## Thread",
        "\n## Single",
        "\n## Pre-publish checklist",
        "\n## Distribution Checklist",
    ]
    cut = len(content)
    for marker in markers:
        idx = content.find(marker)
        if idx != -1:
            cut = min(cut, idx)
    body_budget = max_chars // 2
    sections.append(content[:body_budget].rstrip())
    for marker in markers:
        idx = content.find(marker)
        if idx != -1:
            sections.append(content[idx : idx + 2200].rstrip())
    compacted = "\n\n[...middle truncated for quick copyedit...]\n\n".join(sections)
    return compacted[:max_chars]


def review_one(path: Path, anchors: str, model: str, model_timeout: int, quick: bool = False) -> str:
    content = path.read_text()
    if quick:
        content = compact_markdown_for_quick_review(content)
    prompt = PROMPT_TEMPLATE.format(
        system=QUICK_SYSTEM_PROMPT if quick else SYSTEM_PROMPT,
        anchors=anchors,
        path=path,
        content=content,
    )
    return call_claude(prompt, model=model, timeout=model_timeout)


def review_basename(draft_path: Path) -> str:
    """Compute a collision-safe basename for the review file.

    Two drafts with the same filename in sibling directories (e.g.
    `compare/jira.md` and `integrations/jira.md`) used to collide on
    `jira.review.md` and silently overwrite each other. Prefix the
    basename with the parent directory name when the parent looks
    like a content-surface segment (compare, integrations, blog,
    posts, etc.). Default behavior is unchanged when there's no
    collision risk.
    """
    SURFACE_PARENTS = {
        "compare", "comparisons", "integrations", "integration",
        "blog", "posts", "drafts", "guides",
    }
    base = draft_path.stem.replace(" ", "_")
    parent = draft_path.parent.name
    if parent in SURFACE_PARENTS:
        return f"{parent}-{base}"
    return base


def write_review(out_dir: Path, draft_path: Path, review_md: str) -> tuple[Path, Path | None]:
    """Write the full review file. Optionally split out the interview queue if non-trivial."""
    out_dir.mkdir(parents=True, exist_ok=True)
    base = review_basename(draft_path)
    review_path = out_dir / f"{base}.review.md"
    review_path.write_text(review_md)

    interview_path: Path | None = None
    marker = "## Interview queue"
    if marker in review_md:
        body_after = review_md.split(marker, 1)[1].lstrip("\n")
        if "No interview items" not in body_after.split("\n", 1)[0] and "No interview items" not in body_after[:200]:
            interview_path = out_dir / f"{base}.interview.md"
            interview_path.write_text(
                f"# Interview queue: {draft_path.stem}\n\n"
                f"**Source review:** {review_path}\n"
                f"**Source draft:** {draft_path}\n\n"
                f"---\n\n{marker}{body_after}"
            )

    # Best-effort: append findings to the per-article ledger if the draft
    # resolves to a tracked content slug.
    try:
        import sys as _sys
        _sys.path.insert(0, str(Path.home() / ".config" / "zerg" / "lib"))
        import article_lock as _al  # type: ignore
        slug = _al.file_path_to_slug(str(draft_path))
        if slug:
            n = _al.ingest_review_file(review_path, slug, reviewer="matt")
            if n:
                print(f"[fakematt-copyedit] appended {n} finding(s) to feedback ledger for slug={slug}",
                      file=sys.stderr)
    except Exception as _e:  # noqa: BLE001
        print(f"[fakematt-copyedit] warn: ledger ingest failed: {_e}", file=sys.stderr)

    return review_path, interview_path


def write_session_summary(out_dir: Path, results: list[dict], model: str, started: float) -> Path:
    duration = time.time() - started
    today = dt.date.today().isoformat()
    lines = [
        "# Fake Matt Copyedit — session summary",
        "",
        f"**Date:** {today}",
        f"**Model:** {model}",
        f"**Duration:** {duration:.1f}s",
        f"**Drafts reviewed:** {len(results)}",
        "",
        "## Files",
        "",
    ]
    for r in results:
        lines.append(f"### {r['draft'].name}")
        lines.append(f"- Source: `{r['draft']}`")
        lines.append(f"- Review: `{r['review']}`")
        if r.get("interview"):
            lines.append(f"- Interview queue: `{r['interview']}`  ⚠️ has discussion items")
        else:
            lines.append("- Interview queue: none (all findings HIGH/MEDIUM)")
        lines.append("")
    summary = out_dir / "session-summary.md"
    summary.write_text("\n".join(lines))
    return summary


def maybe_pdf_and_open(files: list[Path], open_files: bool) -> None:
    """Default: do nothing. Caller must opt-in via --open. Per Matt:
    review/interview/summary files are read by Claude and are not for
    auto-opening — they clutter the screen with duplicate windows."""
    if not open_files:
        return
    if not PDF_SCRIPT.exists():
        subprocess.run(["open"] + [str(f) for f in files])
        return
    subprocess.run(["python3", str(PDF_SCRIPT)] + [str(f) for f in files])


def main() -> int:
    p = argparse.ArgumentParser(description="Fake Matt copyedit pass on prose drafts.")
    p.add_argument("drafts", nargs="+", help="Markdown draft paths")
    p.add_argument("--out-dir", default=str(DEFAULT_OUT), help="Output directory")
    p.add_argument("--model", default=None,
                   help=f"Claude model id (default: aitr pick, falling back to {DEFAULT_MODEL})")
    p.add_argument("--model-timeout", type=int, default=DEFAULT_MODEL_TIMEOUT, help="Seconds to wait for the model call before failing")
    p.add_argument("--max-anchor-chars", type=int, default=DEFAULT_MAX_ANCHOR_CHARS, help="Maximum total anchor characters to include before the draft")
    p.add_argument("--no-pdf", action="store_true", help="Deprecated; default is no-open. Kept for backward compat.")
    p.add_argument("--open", action="store_true", help="Open session-summary + review + interview files (off by default — Matt does NOT want these auto-opened).")
    p.add_argument("--quick", action="store_true", help="Skip social-variant deep dive")
    args = p.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    started = time.time()

    # Model resolution: explicit --model > aitr pick > DEFAULT_MODEL (loud fallback).
    if args.model is None:
        total_draft_chars = sum(
            len(Path(raw).read_text(errors="replace")) for raw in args.drafts if Path(raw).exists()
        )
        args.model = aitr_model_or(
            DEFAULT_MODEL,
            task_kind="prose-review",
            caller="fakematt-copyedit",
            quality_floor="high-stakes",
            artifact_size_tokens=total_draft_chars // 4,
        )

    max_anchor_chars = args.max_anchor_chars
    if args.quick and max_anchor_chars == DEFAULT_MAX_ANCHOR_CHARS:
        max_anchor_chars = 10000
    anchors = load_anchors(quick=args.quick, max_anchor_chars=max_anchor_chars)
    results = []
    sent_log_path = Path(__file__).parent / "sent-log.jsonl"
    for raw in args.drafts:
        path = Path(raw)
        if not path.exists():
            print(f"MISSING: {path}", file=sys.stderr)
            continue
        print(f"[copyedit] reviewing {path.name}…", file=sys.stderr)
        # Snapshot input content BEFORE review for the learning loop
        try:
            input_content = path.read_text()
        except Exception:
            input_content = ""
        try:
            review_md = review_one(path, anchors, args.model, args.model_timeout, quick=args.quick)
        except Exception as e:
            print(f"[copyedit] model call failed for {path}: {e}", file=sys.stderr)
            continue
        review_path, interview_path = write_review(out_dir, path, review_md)
        results.append({"draft": path, "review": review_path, "interview": interview_path})
        print(f"  → {review_path}", file=sys.stderr)
        if interview_path:
            print(f"  → {interview_path}  (LOW-confidence items)", file=sys.stderr)
        # Log for learn.py — track if Matt edits the input draft after seeing the review
        try:
            import json as _json
            with open(sent_log_path, "a") as f:
                f.write(_json.dumps({
                    "ts": dt.datetime.now().strftime("%Y%m%dT%H%M%S"),
                    "input_path": str(path.resolve()),
                    "input_content_at_review": input_content,
                    "review_path": str(review_path),
                    "model": args.model,
                    "checked": False,
                }) + "\n")
        except Exception as e:
            print(f"[sent-log] {e}", file=sys.stderr)

    if not results:
        print("No reviews produced.", file=sys.stderr)
        return 1

    summary = write_session_summary(out_dir, results, args.model, started)
    print(f"\n[copyedit] summary: {summary}", file=sys.stderr)

    # Open everything in Preview as one window.
    files_to_open: list[Path] = [summary]
    for r in results:
        files_to_open.append(r["review"])
        if r.get("interview"):
            files_to_open.append(r["interview"])
    maybe_pdf_and_open(files_to_open, args.open)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
