#!/usr/bin/env python3
"""Fake Matt copyedit skill — review prose drafts against writing_style.md + voice fingerprint.

Usage:
    python3 ~/.claude/skills/fakematt-copyedit/run.py <draft.md> [<more.md>...] [flags]

Flags:
    --out-dir DIR     where to write reviews (default: /tmp/fakematt-copyedit/)
    --model MODEL     Claude model id (default: claude-opus-4-7)
    --no-pdf          skip PDF conversion + Preview open
    --quick           shorter review (skip social-variant analysis)
"""
from __future__ import annotations

import argparse
import datetime as dt
import subprocess
import sys
import time
from pathlib import Path

# Use the existing Claude CLI subprocess wrapper from the corpus lib.
sys.path.insert(0, str(Path.home() / ".claude" / "feedback-corpus"))
from lib.claude import call_claude  # type: ignore

DEFAULT_MODEL = "claude-opus-4-7"
DEFAULT_OUT = Path("/tmp/fakematt-copyedit")

VAULT_ROOT = Path(
    "/Users/mattheweisner/Library/Mobile Documents/iCloud~md~obsidian/Documents/Zerg/MattZerg"
)
STYLE_GUIDE = VAULT_ROOT / "writing_style.md"
VAULT_CLAUDE_MD = VAULT_ROOT / "CLAUDE.md"
VOICE_FINGERPRINT = Path.home() / ".claude" / "feedback-corpus" / "voice" / "fingerprint.md"
PDF_SCRIPT = Path("/tmp/md_to_pdf.py")  # generated by the prior PDF-export step; falls back if absent


def load_anchors(quick: bool = False) -> str:
    """Load the corpus that frames the review."""
    parts = []
    if STYLE_GUIDE.exists():
        parts.append(f"# WRITING STYLE GUIDE (canonical)\n\n{STYLE_GUIDE.read_text()}")
    else:
        parts.append("# WRITING STYLE GUIDE — MISSING (proceed with general best practices).")

    if not quick and VAULT_CLAUDE_MD.exists():
        # Just pull the AI Writing Cleanup section to keep tokens tight.
        text = VAULT_CLAUDE_MD.read_text()
        marker = "### AI Writing Cleanup"
        if marker in text:
            section = text.split(marker, 1)[1]
            # End at next ### or end of file.
            end = section.find("\n### ")
            if end != -1:
                section = section[:end]
            parts.append(f"# AI WRITING CLEANUP CHECKLIST (from MattZerg/CLAUDE.md)\n\n{marker}{section}")

    if not quick and VOICE_FINGERPRINT.exists():
        parts.append(f"# MATT'S VOICE/POSITIONING FINGERPRINT (relevant for launch posts)\n\n{VOICE_FINGERPRINT.read_text()}")

    return "\n\n---\n\n".join(parts)


SYSTEM_PROMPT = """You are Fake Matt, doing a copyedit pass on a prose draft for the Zerg blog (or paired social copy).

Your job is to surface issues using the anchors below as ground truth. Your review must be:

- **Structured.** Not Matt-voice cosplay. Plain analytical prose with citations.
- **Cited.** Every finding names the rule it violates (writing_style.md section, AI-cleanup checklist row, or voice-fingerprint principle).
- **Confidence-rated.** HIGH / MEDIUM / LOW per the rubric below.
- **Actionable.** Each finding includes either a concrete rewrite, a discussion question, or an explicit "no action — flagging for awareness."
- **Honest.** Don't invent issues. If a section is good, say nothing about it.

# Confidence rubric

- **HIGH** — Clear violation of a documented rule. The fix is unambiguous; just apply it.
- **MEDIUM** — Pattern the style guide flags, but the fix depends on context. Suggest a default rewrite + note when to keep as-is.
- **LOW** — Voice/intent genuinely uncertain. The fix requires author input. **LOW items go to the INTERVIEW QUEUE for live discussion.**

Bias toward fewer HIGH findings (only when the rule is unambiguous) and willingness to mark LOW (the author should know what's worth talking through).

# Output format (markdown — DO NOT WRAP IN A CODE FENCE)

Output exactly this structure, in this order:

```
# Copyedit Review: <draft title>

**Reviewer:** Fake Matt (copyedit skill)
**Date:** <today YYYY-MM-DD>
**Source:** <full path to draft>
**Anchors:** writing_style.md + AI Writing Cleanup + voice fingerprint

## Summary

- N findings total: X HIGH, Y MEDIUM, Z LOW
- Top issue: <one-sentence headline of the most important finding>
- Quickest wins: <bullet list, 2-4 items, of HIGH-confidence one-liners>

## Findings

For each finding, this exact shape:

### F1 — <one-line title>
**Section:** <where in the draft (e.g., "Full Piece, opening paragraph")>
**Rule:** <writing_style.md section name OR AI-cleanup row OR voice-fingerprint principle>
**Confidence:** HIGH | MEDIUM | LOW
**Quote:** > <verbatim from draft, trimmed if long>
**Issue:** <one-sentence diagnosis>
**Suggested fix:** <rewrite OR discussion question OR "no action — flagging for awareness">

(Number sequentially F1, F2, F3...)

## Interview queue (LOW confidence items only)

If any LOW-confidence findings exist, list them here in numbered form. For each:

### Q1 — <one-line question>
**Source finding:** F<n>
**Why we couldn't decide:** <one sentence>
**What to ask Matt:** <a concrete question he can answer in 1-2 sentences>

If no LOW items, write: "No interview items — all findings are HIGH or MEDIUM confidence."
```

# Scope reminders

- Review the FULL DRAFT (Notes, Full Piece, social variants — all sections present in the file).
- For paired social copy (LinkedIn, thread, single tweet), check that the lead claims match the blog post AND that they aren't lifting the same sentences verbatim from the blog body (LinkedIn has its own line-break rhythm, threads have hook-first/CTA-last shape, single tweet must be ≤280 chars).
- Don't fact-check claims, statistics, or external citations. That's not in scope. Flag only if a number is contradictory within the draft itself.
- Don't suggest hero images, layout changes, or category routing. Prose only.
- Single tweet character budget: count includes the URL. Twitter wraps any link to a 23-char t.co URL — body + 23 must total ≤280.

# Calibrated rules (from prior author interviews — apply, don't re-flag)

- **Catchy-quote repetition policy.** Verbatim cross-format repetition is OK *only* when the line is a genuinely sticky one-liner, capped at 2x per thread. Long sentences and load-bearing claims should be rephrased per format. Don't flag a short, in-voice line repeated ≤2x.
- **Teaser-then-colon constructions** ("It does something most agents skip entirely:") are OK when paragraph rhythm pays them off. Don't flag as a default flatten target. (Different from "Here's what / Here's the thing" which IS banned — see AI Cleanup checklist.)
- **Click-baity scene-setters are banned.** Any opener that starts with "Here's a thing that happens..." / "Here's what happens..." / "Here's the thing about..." is a hard fail per AI Cleanup. Suggest a direct rewrite that lands on the action immediately.
- **Punctuation choices: comma > em-dash by default for non-hook prose.** When in doubt between em-dash and comma in a body sentence, suggest comma (more professional, consistent with Matt's polish bias). Hooks/punch lines may keep em-dashes if rhythm warrants — flag as MEDIUM, not HIGH.
- **"first-class participants/citizens" is jargon, not voice.** Default rewrite toward descriptive: "AI agents that work alongside humans," "the agent gets the same surface as the human," etc. No fixed internal terminology.
- **Endings: "That's the future we're building toward" is in-voice** (per writing_style.md → Idan's Voice → Endings). Don't flag the ending pattern itself; only flag if the line *above* it already concludes (then suggest cutting the redundant penultimate, keeping the close).
- **Watch for splitting-an-em-dash side effects.** When a previous polish replaced "X — Y" with "X. Y", check whether the result introduced (a) redundancy ("X. Y" where Y just restates X), (b) mechanical "X doesn't require Y. It is Z." parallel structure, or (c) a "This matters because…" announcement. These are common artifacts of em-dash splits and should be flagged HIGH if found in recently-polished prose.
- **Filler-word sweep is mandatory.** Always grep the draft for "just", "actually", "very", "really", "quite", "purely", "simply", "entirely", "legitimately", "basically", "essentially". Each instance is a presumed cut unless the word is genuinely doing work. Surface as ONE rolled-up HIGH finding ("filler-word sweep needed: N instances across formats") rather than N separate findings.

# Anchors

The following are the writing standards. Cite them by section name in your findings.

"""

PROMPT_TEMPLATE = """{system}

{anchors}

---

# DRAFT TO REVIEW

**File:** {path}

```markdown
{content}
```

---

# YOUR TASK

Produce the full copyedit review per the format above. Begin output with the `# Copyedit Review:` header. No preamble. No "Here is the review" framing.
"""


def review_one(path: Path, anchors: str, model: str) -> str:
    content = path.read_text()
    prompt = PROMPT_TEMPLATE.format(
        system=SYSTEM_PROMPT,
        anchors=anchors,
        path=path,
        content=content,
    )
    return call_claude(prompt, model=model, timeout=600)


def write_review(out_dir: Path, draft_path: Path, review_md: str) -> tuple[Path, Path | None]:
    """Write the full review file. Optionally split out the interview queue if non-trivial."""
    out_dir.mkdir(parents=True, exist_ok=True)
    base = draft_path.stem.replace(" ", "_")
    review_path = out_dir / f"{base}.review.md"
    review_path.write_text(review_md)

    interview_path: Path | None = None
    marker = "## Interview queue"
    if marker in review_md:
        body_after = review_md.split(marker, 1)[1].lstrip("\n")
        if "No interview items" not in body_after.split("\n", 1)[0] and "No interview items" not in body_after[:200]:
            interview_path = out_dir / f"{base}.interview.md"
            interview_path.write_text(
                f"# Interview queue: {draft_path.stem}\n\n"
                f"**Source review:** {review_path}\n"
                f"**Source draft:** {draft_path}\n\n"
                f"---\n\n{marker}{body_after}"
            )
    return review_path, interview_path


def write_session_summary(out_dir: Path, results: list[dict], model: str, started: float) -> Path:
    duration = time.time() - started
    today = dt.date.today().isoformat()
    lines = [
        "# Fake Matt Copyedit — session summary",
        "",
        f"**Date:** {today}",
        f"**Model:** {model}",
        f"**Duration:** {duration:.1f}s",
        f"**Drafts reviewed:** {len(results)}",
        "",
        "## Files",
        "",
    ]
    for r in results:
        lines.append(f"### {r['draft'].name}")
        lines.append(f"- Source: `{r['draft']}`")
        lines.append(f"- Review: `{r['review']}`")
        if r.get("interview"):
            lines.append(f"- Interview queue: `{r['interview']}`  ⚠️ has discussion items")
        else:
            lines.append("- Interview queue: none (all findings HIGH/MEDIUM)")
        lines.append("")
    summary = out_dir / "session-summary.md"
    summary.write_text("\n".join(lines))
    return summary


def maybe_pdf_and_open(files: list[Path], no_pdf: bool) -> None:
    if no_pdf:
        return
    if not PDF_SCRIPT.exists():
        # Soft fall-through: no PDF script available, just open .md in default app.
        subprocess.run(["open"] + [str(f) for f in files])
        return
    subprocess.run(["python3", str(PDF_SCRIPT)] + [str(f) for f in files])


def main() -> int:
    p = argparse.ArgumentParser(description="Fake Matt copyedit pass on prose drafts.")
    p.add_argument("drafts", nargs="+", help="Markdown draft paths")
    p.add_argument("--out-dir", default=str(DEFAULT_OUT), help="Output directory")
    p.add_argument("--model", default=DEFAULT_MODEL, help="Claude model id")
    p.add_argument("--no-pdf", action="store_true", help="Skip PDF conversion + Preview open")
    p.add_argument("--quick", action="store_true", help="Skip social-variant deep dive")
    args = p.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    started = time.time()

    anchors = load_anchors(quick=args.quick)
    results = []
    for raw in args.drafts:
        path = Path(raw)
        if not path.exists():
            print(f"MISSING: {path}", file=sys.stderr)
            continue
        print(f"[copyedit] reviewing {path.name}…", file=sys.stderr)
        review_md = review_one(path, anchors, args.model)
        review_path, interview_path = write_review(out_dir, path, review_md)
        results.append({"draft": path, "review": review_path, "interview": interview_path})
        print(f"  → {review_path}", file=sys.stderr)
        if interview_path:
            print(f"  → {interview_path}  (LOW-confidence items)", file=sys.stderr)

    if not results:
        print("No reviews produced.", file=sys.stderr)
        return 1

    summary = write_session_summary(out_dir, results, args.model, started)
    print(f"\n[copyedit] summary: {summary}", file=sys.stderr)

    # Open everything in Preview as one window.
    files_to_open: list[Path] = [summary]
    for r in results:
        files_to_open.append(r["review"])
        if r.get("interview"):
            files_to_open.append(r["interview"])
    maybe_pdf_and_open(files_to_open, args.no_pdf)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
